### ISSUE TITLE
Sort/select/filter on ... and do ...

### ISSUE THREAD

**Issue by M66B** [M66B/XPrivacy#1031]
Since sorting, selecting, filtering and doing something are related I am merging all related issues.

Sort on:
- Date installed
- Date modified
- Date submitted restriction

Filter on:
- No permissions

Actions:
- Toggle  (implemented)
- Import (implemented)
- Fetch (implemented)
- Submit (implemented)

**Comment by amynbe** [comment]
Hello,
Please, could you add an option to apply template on all selected apps, not only in the detailed view?

**Comment by M66B** [comment]
@amynbe  you can do this with the batch operations, for which a [pro license](http://www.xprivacy.eu/) is needed.

**Comment by amynbe** [comment]
I would suggest you make this option free, will all respect to your work. Otherwise the free version is nearly unusable for someone who already has many apps installed. Popups are too numerous.

**Comment by M66B** [comment]
IMHO the free version is perfectly usable, only you have to do some more work. That is why the pro features are called convenience features. Your support to the project, just a few dollars/euros is appreciated. I have spent about 2500 hours developing and supporting XPrivacy and believe me the few donations I get are by far a compensation for that. fortunately the project is not about the money, but I like to see some support, so I know I am not doing things for nothing. Note that you can get a free pro license if you contribute to the project.

**Comment by amynbe** [comment]
I understand. I will consider grabbing the license fetcher. But my point about usability was that the template is useless if you have many apps. Honestly I got a little pissed off when, after the overwhelming popups forced me to get to know the template feature, I found out I could not really apply it to my installed apps. I felt that the app was somehow misadvertised as a free-to-use tool.

**Comment by M66B** [comment]
By default on demand restricting is disabled for already installed applications, so I am wondering why you got so many on demand popups.

**Comment by amynbe** [comment]
I activated it.

**Comment by M66B** [comment]
Then you can deactivate it too, or am I wrong?

**Comment by amynbe** [comment]
Why would I? I don't want the apps to be silently blocked. This is not the issue.
