### ISSUE TITLE
GPS Navigation not working

### ISSUE THREAD

**Issue by mbefore305** [M66B/XPrivacy#1105]
Even if nothing is blocked in Xprivacy my GPS Navigation app is not working.

Details:
Xprivacy version 1.11.10
Nothing blocked at all, also not changing any data (like IMEI, etc.)
So basically a clean install of Xprivacy and enabled in the Xposed framework.
App: GPS Navigation & Maps +offline from Skobbler
When I start the app, GPS is not activated (while enabled in system settings), so the app does not get the location.
If I disable Xprivacy and reboot, the app works perfectly fine.
![screenshot_2014-01-14-07-15-20](https://f.cloud.github.com/assets/6396795/1907974/0c3c6452-7ce5-11e3-928f-0056e7a936e0.png)

Logcat:
--------- beginning of /dev/log/main
I/XPrivacy/XActivity( 7541): getSystemService layout_inflater=com.android.internal.policy.impl.PhoneLayoutInflater uid=10240
I/XPrivacy/XActivity( 7541): getSystemService layout_inflater=com.android.internal.policy.impl.PhoneLayoutInflater uid=10240
D/dalvikvm( 7541): create interp thread : stack size=32KB
D/dalvikvm( 7541): create new thread
D/dalvikvm( 7541): new thread created
D/dalvikvm( 7541): update thread list
D/dalvikvm( 7541): threadid=11: interp stack at 0x5dc58000
D/dalvikvm( 7541): threadid=11: created from interp
D/dalvikvm( 7541): start new thread
I/XPrivacy( 7541): Reload fallback restrictions uid=10240 0 ms
I/XPrivacy/XRuntime( 7541): Queue usage data=10240/shell/exec=false size=1
I/XPrivacy/XRuntime( 7541): get 10240/exec shell=!restricted (file)
I/XPrivacy/XRuntime( 7541): get 10240/exec shell=!restricted (cached)
D/dalvikvm( 7541): threadid=11: notify debugger
D/dalvikvm( 7541): threadid=11 (pool-23-thread-1): calling run()
I/XPrivacy/XContextImpl( 7541): getSystemService display=android.hardware.display.DisplayManager uid=10240
I/XPrivacy/XContextImpl( 7541): getSystemService window=android.view.WindowManagerImpl uid=10240
I/XPrivacy/XContextImpl( 7541): getSystemService power=android.os.PowerManager uid=10240
I/XPrivacy/XActivity( 7541): getSystemService power=android.os.PowerManager uid=10240
V/InputMethodManager( 7541): onWindowFocus: null softInputMode=272 first=true flags=#810100
V/InputMethodManager( 7541): START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{43afbe50 V.E..... R.....ID 0,0-720,1280} ic=null tba=android.view.inputmethod.EditorInfo@43aaf3f0 controlFlags=#104
V/InputMethodManager( 7541): Starting input: Bind result=InputBindResult{com.android.internal.view.IInputMethodSession$Stub$Proxy@43aafa88 com.dasur.slideit/.SlideITIME #134}
I/SurfaceTextureClient( 7541): [STC::queueBuffer](this:0x5d388228) fps:0.98, dur:1018.74, max:1018.74, min:1018.74
V/InputMethodManager( 7541): START INPUT: android.widget.ListView{43a60f10 VFED.VCL .F....I. 0,0-720,1134 #102000a android:id/list} ic=null tba=android.view.inputmethod.EditorInfo@43bf9788 controlFlags=#100
V/InputMethodManager( 7541): Starting input: Bind result=InputBindResult{com.android.internal.view.IInputMethodSession$Stub$Proxy@43c3d918 com.dasur.slideit/.SlideITIME #135}

**Comment by kripz** [comment]
How does it currently work? Right now it seems to report a rough location based on what's in your settings. Like up to +/- 5 to Long and Lat.

**Comment by M66B** [comment]
@mbefore305 there is a FAQ about this.
