### ISSUE TITLE
[Feature] Intent for opening app's permissions page

### ISSUE THREAD

**Issue by drsood** [M66B/XPrivacy#1215]
Request for an Intent for opening an app's permission page directly by passing package name in extra field

**Comment by Cerberus-tm** [comment]
@megamorphg This gets the UID from the app that is currently in focus, or at least on my LG G2:
    awk '/Uid:/ {print $2}' /proc/$(pidof $(dumpsys window windows | tee /sdcard/Download/uid.txt | awk '{if(/mCurrentFocus|mFocusedApp/){for(i=1;i<=NF;i++){if(sub(/\/.*/,"",$i)){print $i; exit}} } }'))/status
