### ISSUE TITLE
Allow cancelling timeout of Dialog

### ISSUE THREAD

**Issue by M1cha** [M66B/XPrivacy#1686]
It would be great if it would be possible to cancel the timeout of the permission dialog without making a decision somehow.

The reason for that is that sometimes I see this dialog too late or the shell commands are that long that I can't read them in the given time.

**Comment by IzzySoft** [comment]
I'm having the same problem as @M1cha – might I propose a compromise? To not "holding up system processes", have the action applied on "timeout". But if the user e.g. tapped the timeout bar before that, keep the screen open for reading. In the end, if half an hour later (joking) the user figured a decision to e.g. permanently allow/forbid, that would be stored "for future reference" – else the input is simply ignored (as the action has been taken already).

How does that sound, @M66B ? I've just restored from a backup after a first-time install of Privacy, and got flooded with superuser *and* XPrivacy requests. In the middle of that I was so confused I almost couldn't tell which are which (luckily the background colors were different ;)
