### ISSUE TITLE
Feature Request -- Allow apps to be permanently excluded from restrictions

### ISSUE THREAD

**Issue by shaiay** [M66B/XPrivacy#1794]
While debugging an app I am writing, each time it is re-installed on the device by the debugger (which happens quite a lot), I have to re-clear restrictions.
A feature permanently excluding an application from xprivacy restrictions, would be greatly appreciated for those of us debugging on their personal phone.

Thanks
Shai

**Comment by chdft** [comment]
I ran into this issue today and would like to suggest the following workaround:
XPrivacy does monitor app installations and sets restrictions based on a template for newly installed apps (see https://github.com/M66B/XPrivacy/blob/aa5d9d5c697b4dfe5cb01986d48cf5881a46c200/src/biz/bokhorst/xprivacy/PackageChange.java around line 47). As far as I can tell, it should be possible to compare the package name (which is known and saved in "packageName" in line 39) of the newly installed application to a specific package name specified some preference (before applying the template) and disable all restrictions if it matches.

**Comment by M66B** [comment]
People expect the settings to be gone after removing an application.

Note that updating an application does not erase the existing settings. Your development environment should not delete and install, but update.
