### ISSUE TITLE
whitelist not working in whatsapp, contacts empty

### ISSUE THREAD

**Issue by mdbs** [M66B/XPrivacy#1973]
Hi,

I bought xprivacy 3.1.1 to restrict whatsapp. In xprivacy, I restricted only contacts for whatsapp (blue box checked next to "Contacts" for whatsapp), and allowed all from the "WA" group from an exchange account (menu -> select contacts to allow -> group WA -> all). But, in whatsapp, the contact list is empty even after refreshing, checking/unchecking contacts in xprivacy, reboots, deleting WA cache, or deleting all WA data from android system settings?

The rom is CM 10.

The usage log shows denials for contacts/contacts/raw_contacts and contacts/contacts/data.

Hints on how to solve this would be very welcome...

**Comment by retorquere** [comment]
How does the whitelist work anyhow? I've bought pro but I can't find it.

**Comment by M66B** [comment]
In the om demand popup you will find extra entries to allow/deny restriction with specific data (filename, etc). You can manage whitelist entries created this way from the application details view. There is a special icon indication a restriction has a whitelist.

**Comment by retorquere** [comment]
Is there documentation on how to configure this? I haven't seen any popups.

**Comment by M66B** [comment]
See here: https://github.com/M66B/XPrivacy#FAQ34

**Comment by retorquere** [comment]
Ah sorry, I didn't express myself  correctly; I know about the on-demand
popups, but I can't find my way from the on-demand popup for contact access
to whitelisting specific (groups of) contacts.

**Comment by M66B** [comment]
There are no on demand popup for contact whitelisting.
You can manage allowed contacts using a menu in the application details view.

**Comment by retorquere** [comment]
Ah: menu -> select contacts to allow. Sorry, I did miss that. It only lists "My contacts" and "starred"; is there a way to have it pick up the other contact groups?

**Comment by M66B** [comment]
All the contact groups Android provides to XPrivacy are shown. If not everything is there, there is little what can be done.

Your inquiries do not concern a bug, so please continue on the XDA XPrivacy forum, which is for questions and general help.
