### ISSUE TITLE
Xprivacy conflicts with latest TextSecure version

### ISSUE THREAD

**Issue by skibbipl** [M66B/XPrivacy#2060]
Hello,
Recently TextSecure that I use as default SMS app stopped working. After some investigation it seems that Xprivacy is the culprit. Can you help us solving this issue? Please check: https://github.com/WhisperSystems/TextSecure/issues/2137

Regards

**Comment by Elbchillharmonie** [comment]
I'm unsure, it might be a different problem. Even after downgrading to 3.4, I still could not receive messages. Only a re-registration of my mobile number made TextSecure fully functional again. However, I'll stay with XPrivacy 3.4 for the time being.
