### ISSUE TITLE
[Request] Add "Manage whitelist" to the usage data menu

### ISSUE THREAD

**Issue by Cyclu** [M66B/XPrivacy#2093]
it should be great to have "manage whitelist" in the menu in usage data log because for now to manage our whitelist we have constantly move between usage log and detailed view>menu

**Comment by M66B** [comment]
Long press uid to manage white/black lists.

**Comment by M66B** [comment]
@Cyclu  Could you please try this version:
https://crowd.xprivacy.eu/XPrivacy_3.6.5-1.apk
