### ISSUE TITLE
GPS stays on continously

### ISSUE THREAD

**Issue by xtrepx** [M66B/XPrivacy#2105]
When denying the location through XPrivacy the GPS stays on continously, showing always the GPS icon and making the battery drain. The only solution is to close the application (remove it from background) but that's not a real solution. If I allow the location, then after 4-5 seconds the GPS is no longer used and the icon is gone.
Attached you have the logcat debug. The 1st one is when Location is allowed, while the 2nd one is with the problem - location denied, GPS always on.
Device: Samung G901F, ROM is G901FXXU1ANH6_G901FORL1ANH1_ORL
Application ID to look for 10070
Attached also a screenshot of about window.
![screenshot_2015-01-04-18-39-27](https://cloud.githubusercontent.com/assets/10390897/5606651/3a8f6268-9441-11e4-970f-83bd91232492.png)

https://mega.co.nz/#!8oxF0JLJ!CgRhaRwwsJye6ntachnMWWQvlL8gQoAue_l8-AyXny4

**Comment by M66B** [comment]
Please post a screenshot of the XPrivacy about too.

**Comment by xtrepx** [comment]
Done

**Comment by M66B** [comment]
I don't see the screenshot, where is it?

**Comment by xtrepx** [comment]
It's in the first topic, I see it loaded

**Comment by M66B** [comment]
Could you please install this version of XPrivacy:
https://crowd.xprivacy.eu/XPrivacy_3.5.9proxy.apk

and capture two new logcats using this command:

'''
logcat | grep proxy.*uid=10070
'''

Also, please post a link to the application you are testing with.

Example output:

```
adb logcat | grep proxy.*uid=10070
I/XPrivacy/XLocationManager(  832): proxyLocationListener uid=10070
I/XPrivacy/XLocationManager(  832): proxyLocationListener uid=10070
I/XPrivacy/XLocationManager(  832): proxyLocationListener uid=10070
I/XPrivacy/XLocationManager(  832): unproxyLocationListener uid=10070
```

I like to know if *unproxyLocationListener* is missing in different scenarios.
Also try to close the application (both in a normal way or forced, for example using the XPrivacy kill menu)

**Comment by xtrepx** [comment]
With Location allowed:

05212: proxyLocationListener uid=10070
06538: proxyLocationListener uid=10070
07164: proxyLocationListener uid=10070
06538: unproxyLocationListener uid=10070
07164: unproxyLocationListener uid=10070


With Location denied:
14640: proxyLocationListener uid=10070
15966: proxyLocationListener uid=10070
16592: proxyLocationListener uid=10070
15966: unproxyLocationListener uid=10070
16592: unproxyLocationListener uid=10070

Application closed normally and forced. However, behavior is the same as before the update. Application link: https://play.google.com/store/apps/details?id=com.shazam.android

**Comment by M66B** [comment]
After *unproxyLocationListener* the GPS should go off, isn't that the case?

**Comment by xtrepx** [comment]
Unfortunately no. I'll try to record so that you can see the behavior.

**Comment by xtrepx** [comment]
Here it is. https://www.youtube.com/watch?v=bwA1ZUNNhFo&feature=youtu.be

**Comment by M66B** [comment]
I could reproduce this issue in compatibility mode (only).
After several hours of debugging I found a solution.
Could you please check if this version solves the problem and if fake locations are still working?
https://crowd.xprivacy.eu/XPrivacy_3.5.9altproxy.apk

**Comment by xtrepx** [comment]
I really appreciate your help. Indeed with this version the bug is fixed. Also the fake location is working fine.

**Comment by M66B** [comment]
Thanks for reporting back.

I will release this version as a new beta release to make sure there are no side effects.

You can always show your appreciation by donating something:
http://www.xprivacy.eu/

**Comment by xtrepx** [comment]
Already donated a while ago, but haven't installed yet the PRO license file. Thank you Marcel
