### ISSUE TITLE
Use faster method for loading app list

### ISSUE THREAD

**Issue by Mosrite** [M66B/XPrivacy#2106]
I'm not a programmer so I don't know if my request is complete nonsense but I'll try it anyway:
Since I have more than 200 apps installed it takes quite a while every time I start XPrivacy until all apps are loaded and I can finally use it. I have no idea how, but Titanium Backup seems to use a method to list all apps within a few seconds (at least in the pro version).
Maybe XPrivacy could use the same method as Titanium Backup for loading the app list? Alternatively, the app list could be loaded in the background or won't be loaded at all until requested by the user. So, if you just want to access the general settings, you won't have to wait until all apps are loaded.

Thanks for considering my suggestion! :)

**Comment by M66B** [comment]
This has already been discussed frequently.

The loading of the application list is not what takes time, but fetching about 400 restrictions and settings for each application from the privacy service is what takes time and this cannot be changed.

Please read this:
https://github.com/M66B/XPrivacy#support

**Comment by Mosrite** [comment]
I'm sorry! I really used the search function but I couldn't find anything related. Sorry for bothering about this!
