### ISSUE TITLE
Restrictions remain applied on cleared app

### ISSUE THREAD

**Issue by PatoAU** [M66B/XPrivacy#2111]
After cleaning all restrictions of the app Airaudio, Xprivacy continues to apply restrictions, making the Airaudio application unusable. 

Xprivacy version 3.5

Screenshots here:
http://imgur.com/9Q5Yh44
http://imgur.com/j6V6eRU
http://imgur.com/kv1o2XQ
http://imgur.com/xe50Scc

**Comment by M66B** [comment]
This can also be caused by restrictions of another application. Check the usage data, follow the procedure in the FAQ or ask for help on XDA. This is most probably not a bug.
