### ISSUE TITLE
Additional 00:00 in the fake MAC address 

### ISSUE THREAD

**Issue by Cyclu** [M66B/XPrivacy#2112]
Allow Internet/NetworkInterfaces.getNetworkInterfaces and restrict Network/NetworkInterface.getHardwareAddress for Network Info II
switch on WiFi then go to Interface tab under wlan0 the MAC adress
appears like this 00:00+fake adress MAC.
 
Screenshot attached:
![screenshot_2015-01-13-12-30-25](https://cloud.githubusercontent.com/assets/6185973/5722589/aceb6d0e-9b3d-11e4-924b-e49bd54cc0ab.png)

Network Info II link:
https://play.google.com/store/apps/details?id=aws.apps.networkInfoIi&hl=en

**Comment by M66B** [comment]
A MAC address is six pairs of hexadecimal digits:
http://en.wikipedia.org/wiki/MAC_address

Relevant code:
https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/PrivacyManager.java#L973

**Comment by Cyclu** [comment]
I know about six pairs of digits for address MAC but like I said I have two pair of zero 00:00
before six pairs of digits of my fake address "C0" in the screenshot is the first pair.

**Comment by M66B** [comment]
If I enter six pairs of digits (separated by a colon) it works for me, no zeroes.

**Comment by Cyclu** [comment]
Install this application: https://play.google.com/store/apps/details?id=net.he.networktools&hl=en

Allow Internet/NetworkInterfaces.getNetworkInterfaces and Network/NetworkInterface.getInterfaceAddresses and restrict Network/NetworkInterface.getHardwareAddress for Network Tools
switch on WiFi then go to Interface Information as you see in the screenshot
all interfaces have two pairs of zeroes before fake address MAC

Screenshot attached:
![screenshot_2015-01-14-11-44-16](https://cloud.githubusercontent.com/assets/6185973/5740030/f699156a-9bff-11e4-8feb-6faf47c5874b.png)

PS. I have that problem on both device HTC OneM8 4.4.4 and HTC OneS 4.2.2
I have tried also with application specific settings with the same result.
Maybe you have different result in AOSP mode because personnaly I'm in compatibility mode?

**Comment by M66B** [comment]
As said, a MAC address is six pairs of hexadecimal digits:
http://en.wikipedia.org/wiki/MAC_address

**Comment by Cyclu** [comment]
![screenshot_2015-01-15-10-48-17](https://cloud.githubusercontent.com/assets/6185973/5755613/eb8c258e-9ca6-11e4-8ada-1e554477a6a3.png)

I hope you will understand me now with this screenshot is done with specific application settings before I simply hid the last few digits because the fake MAC is which I use actually. I can count anyway :)

**Comment by M66B** [comment]
I understand you perfectly, but despite this application is showing eight pairs of hex digits of a MAC address, a MAC address consists of six pairs of hex digits: http://en.wikipedia.org/wiki/MAC_address

**Comment by Cyclu** [comment]
Here is the proof that XPrivacy precisely the functions Network/NetworkInterface.getHardwareAddress  add two pairs of zero for the network interface and not for WiFI info.

I have defaced the MAC address completely in the main settings see the result for Network Interface
two pairs of zeroes before DE:FA:CE:DE:FA:CE

![screenshot_2015-01-15-14-04-01](https://cloud.githubusercontent.com/assets/6185973/5758611/1bd44ce2-9cc7-11e4-9781-71a3d87c20ad.png)

WiFi info tab no zeroes before DE:FA:CE:DE:FA:CE here:

![screenshot_2015-01-15-14-04-21](https://cloud.githubusercontent.com/assets/6185973/5758682/a58b9260-9cc7-11e4-9dc3-687903a2019c.png)

Here in the applications specific settings I tried with only four pairs of digits for address MAC like you see in the first screenshot four pairs of zeroes are added for network interface instead two pairs (I didn't know that XPrivacy complete the MAC address with the zeroes) like for WiFi info tab in the second screenshot.

First screenshot:
![screenshot_2015-01-15-13-54-46](https://cloud.githubusercontent.com/assets/6185973/5758842/381f9472-9cc9-11e4-9622-6d6a76fa14ba.png)

Second screenshot:
![screenshot_2015-01-15-13-54-56](https://cloud.githubusercontent.com/assets/6185973/5758873/6f434322-9cc9-11e4-9bb6-ad8430f63b80.png)

I have tried with three applications with the same result. (the third app is WiFi Connect Info):
https://play.google.com/store/apps/details?id=jp.webware.WifiConnect&hl=en
When the functions Network/NetworkInterface.getHardwareAddress is unrestricted I get my true MAC address properly with six pairs of hexadecimal digits.

**Comment by M66B** [comment]
As said, it works for me and a MAC-address is 6 pairs of hexadecimal digits. I have tested with Network info II and for fake values it doesn't matter if XPrivacy is running in compatibility mode or not.

If you enable debug logging in the XPrivacy settings, you can see in the catlog which fake values XPrivacy provides.

**Comment by Cyclu** [comment]
No matter MAC address has 6 pairs of hexadecimal digits there are a problem for me I wonder why I have that problem and why in WiFi info tab the fake address MAC does not have these pairs of zeroes.
Have you tried "he.net Network Tools" it is more recent than Network Info II:
https://play.google.com/store/apps/details?id=net.he.networktools&hl=en 

I would resolve this problem anyway maybe I will ask the question in the Xda thread if someone has the same result it's not possible that all applications have false result no? 

In the logcat I have to search the entry like this right?:
Get client 10186/Network/NetworkInterface.getHardwareAddress(null;null) network=restricted(cached)0ms 
of course I have to enter specific MAC settings for app because "null" is global settings right too?

**Comment by M66B** [comment]
The HE application also shows 8 pairs of digits, but this is incorrect, since a MAC address has only six pairs of digits. This is not an XPrivacy problem.

**Comment by wbedard** [comment]
Just to briefly chime in on this issue...

While I have been able to confirm the behavior described in both apps mentioned in this thread (Network Info II and HE's Network Tools), I have also confirmed that XPrivacy is logging a correctly formatted MAC address to those apps (i.e. 6 pairs of hex chars).  However, since both apps do display correctly formatted MAC addresses when "getHardwareAddress" isn't restricted, it seems "non-intuitive" (I'm being deliberately kind here...) to say that the problem isn't caused by XPrivacy.

Since you are more familiar with the code than I am, would you confirm that the data being passed through the actual interface to the application (as opposed to what is displayed in the logcat info...) is correctly formatted according to the Android API specification?  To say that both of these highly regarded apps share a similar bug (that is core to their basic functionality) really make you come across as "unreasonable" and I doubt you what that.

**Comment by M66B** [comment]
The code is here:
https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/XWifiManager.java#L142
The Android source code is here:
http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.0_r1/android/net/wifi/WifiInfo.java#387
The fake value is here:
https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/PrivacyManager.java#L974

There is nothing wrong with the code IMHO.
The logging confirms this.
