### ISSUE TITLE
volume up button freezes the some apps ?

### ISSUE THREAD

**Issue by rezad1393** [M66B/XPrivacy#2115]
i use xprivacy on samasung note 10.1 2014 3g edition.
when i am in some apps like google hangouts or Duolingo (some games too but not all apps) and i try to up the volume with volume up key the system freezes for about 5 seconds and then it show the volume changing bar on screen. if i do this more than once sometimes i get "system stopped responding.do you want to close it?" with ok and wait options.

unchecking the app in xprivacy this issue doesnt appear`

**Comment by M66B** [comment]
Please read here:
https://github.com/M66B/XPrivacy#limitations

**Comment by rezad1393** [comment]
oh hi
as i said i am new at this so forgive me for this.
it is android limitation? 
it happens only with volume up and it happens on some apps only and i can see that there is a prompt for getsubscriberid .this prompt appears in booth apps i mentioned.maybe its related to that?

**Comment by M66B** [comment]
It is a known and documented problem, which can unfortunately not be fixed.

**Comment by rezad1393** [comment]
if i remove the question mark from getsubscriberid this fixes it.
maybe it helps others too?
unless this happens on other prompts too.
but i just see it on before that prompt and as i said changing that option removes this issue.
i dont know why volume up prompt that but i think as you said its android related(however weird)
