### ISSUE TITLE
[bug] Usage data not saved in database after reboot was initiated

### ISSUE THREAD

**Issue by danielmmmm** [M66B/XPrivacy#2119]
Some apps trigger the intent firewall (e.g. due to dismounting of SD-cards) when rebooting (a real reboot, not a soft reboot). The on-demand dialog is showing up behind the Android reboot pop-up and (naturally) cannot be interacted with. Unfortunately, these intents cannot be white/black-listed after the reboot completed, because they do not appear in the usage data.

I initiated a reboot at 11:29:05 and XPrivacy showed 3 on-demand pop-ups before the phone finally rebooted. After the reboot, the usage data shows a gap from 11:28:37 to 11:33:51. The events from 11:29:xx are missing.

Marcel, it would be nice if you could fix this. But I would not be disappointed if you won't if the underlying reason makes things too complicated.

**Comment by an0n981** [comment]
a workaround: capture a log during shutdown and then add the entries into the database, if you need hep with the proper commands, let me know.

**Comment by danielmmmm** [comment]
Thanks! I am not that familiar with SQL commands, but I think I could figure out how to add the correct entries with SQLite Database Browser.

**Comment by M66B** [comment]
There is nothing I can do to fix this.

**Comment by danielmmmm** [comment]
Alright, I'll try my luck with SQL :-)
