### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by maidik** [M66B/XPrivacy#2120]
While on the main screen (shown), clicking the pulldown (labelled "all" currently) crashes the app.  This is the only behaviour I can get from it.  Click that, app crashes.  Consistently.

I've attempted a data and cache dump.  That doesn't change anything.

I currently have every optional part installed.  (xpriv xposed mod, xpriv pro license fetcher, xpriv installer...)

SM-N900v, 4.4.2, rooted, stock ROM.

https://drive.google.com/file/d/0B4QPGjaKXDdqTkFxeV8wNFZOWEk/view?usp=sharing
https://drive.google.com/file/d/0B4QPGjaKXDdqVENXWXlzbGFta28/view?usp=sharing

**Comment by M66B** [comment]
Which version of XPrivacy are you using?

**Comment by maidik** [comment]
3.6. However this was happening with 3.5 and maybe previous versions.

**Comment by M66B** [comment]
I am currently on a slow mobile connection, so I cannot download the log files. Maybe you can find the crash by looking for FATAL and only post the crash and a few dozen lines around it.

**Comment by maidik** [comment]
Hmm..."fatal" doesn't turn up anywhere.  The error thrown is "Unfortunately, XPrivacy has stopped."  Any other term I should search for?

**Comment by M66B** [comment]
The other term to search for is exception, but there are potentially more of them, but unrelated, so check if at least the first stack trace frame is of XPrivacy.

A better method is to reproduce the crash while watching the catlog and stopping the log right after the crash.

**Comment by M66B** [comment]
I would like to look into this, but there is no crash or exception in the provided log files.

**Comment by maidik** [comment]
I understand.  As soon as I have time, I'll plug in an do I proper logcat.  I'm not sure how to do one without sitting down at my desktop.

**Comment by an0n981** [comment]
https://play.google.com/store/apps/details?id=com.nolanlawson.logcat

**Comment by maidik** [comment]
Perfect...except now it's not crashing?! This was an issue for like six months! I don't even...

I guess I'll post here if it comes back.
