### ISSUE TITLE
What does identification/SERIAL stand for?

### ISSUE THREAD

**Issue by tuliogit** [M66B/XPrivacy#2121]
I've done a research and I feel this information is new for me. Some apps try to access identification/SERIAL. I know what IMSI is, what IMEI is, and I also know they are NOT related to this string, since they have their own string (and, if I'm right, they are in "phone/", not in "identification").
So can anybody explain what this string stands for, and what makes it different from the SIM card ID and the Phone IMEI?

**Comment by M66B** [comment]
Questions like this should be asked here:
http://forum.xda-developers.com/xposed/modules/xprivacy-ultimate-android-privacy-app-t2320783

**Comment by tuliogit** [comment]
Found it: http://forum.xda-developers.com/showpost.php?p=56231935&postcount=12394
Thanks
