### ISSUE TITLE
Kill function kills system UI

### ISSUE THREAD

**Issue by J316** [M66B/XPrivacy#2124]
Every time I kill an app from within XPrivacy the system UI force closes and I'm kicked out to the lockscreen, this happens for every app and doesn't happen when I kill the app from app info.

**Comment by M66B** [comment]
I couldn't find a problem in the logcat you have sent me by e-mail. I did see you are using AppOps. Not to be unfriendly, but I don't support XPrivacy in conjunction with other similar product, it is just too difficult to do so.

Please try to capture another logcat with XPrivacy logging enabled (main settings) and AppOps disabled and try to capture only the crash and a few dozen lines around it. It is no fun to look through long logcats not knowing what to search for.

**Comment by J316** [comment]
AppOps is integrated into the ROM, it can't be disabled, but nothing is restricted, in fact this is the very first time I'm having this problem, but AppOps has always been there. Also I'm sorry but I can't recognize the line of the problem in the logcat, but that logcat started 2 seconds before I killed an app and recorded what happened during the time the UI restarted, after the phone was functional I terminated the logcat, so it should be the minimum.

**Comment by J316** [comment]
It looks like the problem suddenly disappeared for I don't know what reason. Oh, well, whatever
