### ISSUE TITLE
Automatic keyboard for search

### ISSUE THREAD

**Issue by ReHung** [M66B/XPrivacy#2128]
Tapping the search button, please activate the Keyboard automatically => one click less!

**Comment by M66B** [comment]
I have already spent time on this, but this is not possible.

**Comment by Magissia** [comment]
Hello, I am curious to know why this is not possible, could you share some details? 


-------- Message d'origine --------
De : Marcel Bokhorst <notifications@github.com>
Envoyé: 31 janvier 2015 12:21:35 CET
À : M66B/XPrivacy <XPrivacy@noreply.github.com>
Objet : Re: [XPrivacy] Automatic keyboard for search (#2128)

I have already spent time on this, but this is not possible.

---

**Comment by M66B** [comment]
There is no API for it.
http://developer.android.com/reference/android/support/v7/widget/SearchView.html

**Comment by Magissia** [comment]
Meaning rare applications having this feature had a hard time implementing it ?

**Comment by M66B** [comment]
Possibly and since the support library represents what is coming on Lollipop, this will be standard behavior in the future (material design requires using the support library).
