### ISSUE TITLE
Version 3.6 fails to protect location

### ISSUE THREAD

**Issue by anilatx** [M66B/XPrivacy#2129]
Problem is reproducible: reverting to 3.5 solves it, reinstlalling 3.6 makes it reapear.
Usage data in both cases suggests that Srv_requestLocationUpdates was restricted, but with 3.5 location in app is supplied by XPrivacy, while in 3.6 application uses real location

**Comment by M66B** [comment]
Please provide a logcat.
I will not look at very long logcats, so please capture only the part where the restriction is being used.
Don't forget to enable XPrivacy debug logging (main settings).
Also please mention your device/ROM/Android version.

**Comment by M66B** [comment]
Version 3.5/3.6 differences:
https://github.com/M66B/XPrivacy/compare/3.5...3.6

**Comment by M66B** [comment]
Please capture a logcat with this special version:
https://crowd.xprivacy.eu/XPrivacy_3.6-1.apk

I have inspected the code and I don't see anything which can explain this.
10,000s of people are using version 3.6 and nobody complained, so it is not very likely there is a bug, but you'll never know.

**Comment by anilatx** [comment]
It's Nexus5/Stock 4.4.4 with 3.4.88-franco.Kernel
Log: http://pastebin.com/gMkHjgqc

This looks suspicious:
W/XPrivacy(32575): java.lang.ClassCastException: android.location.ILocationListener$Stub$Proxy cannot be cast to android.location.LocationListener uid=1000
W/XPrivacy(32575): java.lang.ClassCastException: android.location.ILocationListener$Stub$Proxy cannot be cast to android.location.LocationListener
W/XPrivacy(32575): 	at biz.bokhorst.xprivacy.XLocationManager.a(SourceFile:344)
W/XPrivacy(32575): 	at biz.bokhorst.xprivacy.XLocationManager.a(SourceFile:205)
W/XPrivacy(32575): 	at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.beforeHookedMethod(SourceFile:490)
W/XPrivacy(32575): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
W/XPrivacy(32575): 	at com.android.server.LocationManagerService.requestLocationUpdates(Native Method)
W/XPrivacy(32575): 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:71)
W/XPrivacy(32575): 	at android.os.Binder.execTransact(Binder.java:404)
W/XPrivacy(32575): 	at dalvik.system.NativeStart.run(Native Method)

**Comment by M66B** [comment]
Indeed, that is the problem.
Could you please try if this version fixes the problem?
https://crowd.xprivacy.eu/XPrivacy_3.6-2.apk

**Comment by anilatx** [comment]
No, it makes the app crash on
java.lang.IllegalArgumentException: argument 2 should have type
android.location.ILocationListener, got
biz.bokhorst.xprivacy.XLocationManager$ProxyLocationListener 02-01
15:40:11.863 E/AndroidRuntime(4656):

full log: http://pastebin.com/FnzipNY6

**Comment by M66B** [comment]
Could you please give it another try with this version:
https://crowd.xprivacy.eu/XPrivacy_3.6-3.apk

I have partly reverted the changes for #2105 now.

**Comment by anilatx** [comment]
This version works correctly, thanks!
