### ISSUE TITLE
PHONE_STATE permission chained

### ISSUE THREAD

**Issue by J316** [M66B/XPrivacy#2132]
It looks like the phone/android.intent.action.PHONE_STATE and the calling/android.intent.action.NEW_OUTGOING_CALL permissions are chained between apps. I try to explain, let's say I have 5 apps using the PHONE_STATE permission, I deny it for 1 of them, then, when I get a phone call XPrivacy processes the 5 intents in this order (allow, allow, deny, allow, allow). The result is the first two apps can see the number I've been called by, the third can't, because I restricted it, but the forth and the fifth see the defaced number the third app has been fed with, so it's like they are restricted too. The same goes when I call. I hope it's clear.

**Comment by M66B** [comment]
Please provide a logcat of this with XPrivacy debugging enabled.

**Comment by J316** [comment]
![img_20150205_224620](https://cloud.githubusercontent.com/assets/8670476/6070125/407eec4a-ad8a-11e4-8a1c-adfbddb1d46e.jpg)

This shows exactly what I described, I called the number 000000 for testing purpose, only one app was restricted, but all the apps processed after that were fed with those defaced data.

**Comment by M66B** [comment]
Does XPrivacy run in AOSP or compatibility mode?

**Comment by J316** [comment]
AOSP

**Comment by J316** [comment]
It looks like the same applies for contacts, in particular I get empty contact list in Viber app, like I have no contacts saved at all

**Comment by Tragen** [comment]
Does this happen on 3.6.x only or also on older versions?

**Comment by M66B** [comment]
I have changed the code to block the intents instead of changing the phone number to fix this problem. There is no other way of doing this, but the result is the same, an application cannot see your phone numbers.

Could you please check if this version solves the problem:
https://crowd.xprivacy.eu/XPrivacy_3.6.1-1.apk

The contact restriction is handled in another way, so I don't think this problem applies to contact restrictions (unless you restrict contacts for the contacts application/service itself).

**Comment by M66B** [comment]
@Tragen: this will happen in any version 3.x

**Comment by J316** [comment]
It works, at least for outgoing calls, I didn't try for incoming calls. Now the restricted apps are not fed with fake data but with empty data

**Comment by J316** [comment]
Will be possible in the future to keep feeding apps with fake data?

**Comment by M66B** [comment]
Not for these two restrictions.

**Comment by kbtomo** [comment]
How i can fix or repair my Samsung SM-N9006 mobile phone from installing ROM MANANGER by JRummy and i accedentaly edit the Customise Build Verno setting in wrong procedure and aslo in Reboot Setting i accidentaly set in Reboot Start UI, after all i click the command reboot in my mobile phone, and rebooting was done my mobile phone is Stock in Mobile System Restarting and i try to Backup User Data and Restore User Data in my phone System Recovery but its still not working?
