### ISSUE TITLE
Syncronize xposed prefs with appops

### ISSUE THREAD

**Issue by KOLANICH** [M66B/XPrivacy#2137]
I think that it'd be good if appops prefs are in sync with xprivacy to provide fallback for the case when xprivacy got disabled due differrent reasons. appops policy should be more or equal restrictive than xprivacy one because it's better to degrade functionality a little than leak data.

**Comment by M66B** [comment]
Sorry, this is too much work to implement.

**Comment by M66B** [comment]
It would also be difficult to map XPrivacy restrictions to AppsOps, difficult to maintain (changes in AppsOps will require changes in XPrivacy) and I suspect the number of people interested in this would be very limited.
