### ISSUE TITLE
Fix descriptions

### ISSUE THREAD

**Issue by KOLANICH** [M66B/XPrivacy#2138]
The descriptions refferering google api docs are not comfortable. It should be possible to see what every API does right in xprivacy.

**Comment by M66B** [comment]
It is too much work, it will take space and it will be difficult to maintain, so this will not be done, sorry.

**Comment by KOLANICH** [comment]
>It is too much work
is it too much work to automate this?

**Comment by M66B** [comment]
It would be difficult to extract the right pieces of text, but the idea is not bad. Nevertheless, I am still not going to do this.
