### ISSUE TITLE
Permission request popup while the pulldown bar is pulled down makes the system unusable.

### ISSUE THREAD

**Issue by kitambi** [M66B/XPrivacy#2145]
Exactly as it says - if the notification bar is pulled down when a "restrict on demand" popup is displayed, the UI refuses to accept any input until the popup times out.  If there is more than one popup, every one must time out before the system will accept user input again.  The notification drawer should be dismissed before displaying the popup in order to avoid this issue.

Issue is occurring with build 3.6.6 (468) - Android 5.0.2.

**Comment by M66B** [comment]
This is a known problem, which cannot be solved, see the limitations section.
