### ISSUE TITLE
Stuck at boot after install

### ISSUE THREAD

**Issue by 2edff206** [M66B/XPrivacy#2148]
Hello,
I am using a HTC One with Android Revolution HD rom 90. I have the last version of xposed for Lollipop installed on my phone and I installed the last version of Xprivacy. Then I rebooted my phone to activate it, but I got stuck on bootscreen (HTC logo). Hopefully I was able to get to recovey, so I deleted everething I could find related to Xprivacy (/data/app, ect) and it seemed to work (now the phone passed the boot screen and is "updating android, optimisation app xx out of xxx"). Thanks for you incredible work, I hope you make work again, Xprivacy is a must-have app on android!!

**Comment by M66B** [comment]
For me this works and without logcat there is little I can do.

**Comment by 2edff206** [comment]
No offense but how can "this works" when I can't even acces my phone? And sorry for not giving a logcat I didn't know how to, at least you know about the problem

**Comment by M66B** [comment]
Even with a bootloop it is almost always possible to capture a logcat from a PC. There is a FAQ about how to capture a logcat.

**Comment by M66B** [comment]
Question: did you modify the kernel image as described in the installation instructions?

**Comment by M66B** [comment]
http://pastebin.com/UpVezYzx

**Comment by dethknite** [comment]
** Full log of what occurs in 1 unique loop of xprivacy boot loop **
http://pastebin.com/kH3FBG3z

Boots ok with xprivacy disabled:
http://pastebin.com/h6UTH5bf
http://pastebin.com/7P1fF9ry (includes xposed in filter)

Boot loop after checking it and soft reboot / or rebooting:
http://pastebin.com/0T64MN56
http://pastebin.com/DAwEuyh0 (includes xposed in filter)

**Comment by Primokorn** [comment]
I notice the same issue on BlissPop and Screw roms (stuck on the boot animation). My device boots fine on CM12 though.

**Comment by DarylRunco** [comment]
Hi,
Updated my HTC One to 5.0 today, and saw Xposed framwork & Xprivacy not working. Damn. I found your repository and an updated binary, installed it along XPosed 2.7 experimental (without reading the note, ofc >_>)

After my phone's reboot, XPrivacy was still not working. Damn again. I saw the note, extracted the `boot_signed.img` from HTC RUU (using the `AndroidImageKitchen` tool), patched the kernel, installed it on my device. Stuck on boot. Took a logcat of the freeze (seems to be a crash, not sure if related but don't know what caused it?)

I hard rebooted my phone in recovery (i installed TWRP before anything else), deleted everything related to XPrivacy (data and binary), rebooted and my phone started again (with the modded kernel.)

logcat of the phone stuck available here: http://pastebin.com/ZvmNzW0W

**Comment by aOryx** [comment]
I manually added the service
My logcat dose NOT show error "avc:  denied  { add } for service=xprivacy453 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_service:s0 tclass=service_manager"
but my device still bootloops
What other permissions does xprivacy453 need, so Id play with selinux rules and see?

**Comment by aOryx** [comment]
I added file and service rules to SELinux and i didnt get any errors in my logs but still not booting
anyone have can point me to where the problem could be?
Thanks

Logs Not filtered                                                       >>>> http://pastebin.com/SgcPGSee

logs filtered tages xposed, selinux, xprivacy, avc    >>>>  http://pastebin.com/zTaDK06W
