### ISSUE TITLE
Installation instructions for Lollipop

### ISSUE THREAD

**Issue by chr4** [M66B/XPrivacy#2149]
First, thanks for putting so much efford in XPrivacy, an awesome app!

The installation instructions for Lollipop are ambigous (?)
As far as I understood, XPosed is not required, but a new context for SELinux.
In the README, it looks like after patching SELinux context and installing XPrivacy (step 3) it's still required to install XPosed (step 6) even though that's not possible on Lollipop.
Are the steps 4-8 required for a Lollipop installation?

Furthermore, I tried installing XPrivacy-3.6.6 on cm-12 (after patching SELinux), but XPrivacy just tells me that it wasn't enabled in XPosed. Does that mean my SELinux patch doesn't work? Or is there any other thing I've been missing?

**Comment by M66B** [comment]
XPrivacy always needs Xposed. The steps are numbered for a reason. For Lollipop there is just an additional step.

Note that both Xposed and XPrivacy for Lollipop are early test versions and things might not work. Use the XDA XPrivacy forum to ask if things work for your device/ROM/kernel (I only have one device/ROM myself).
