### ISSUE TITLE
DNS resolving not catched (Lollipop)

### ISSUE THREAD

**Issue by BlueMax** [M66B/XPrivacy#2156]
There might be an alternative code flow in Android 5 for Internet access/DNS resolving. Most apps don't seem to trigger InetAddress (InetAddress.getAllByName) APIs anymore. Instead there's just one call to 'LinkProperties.getLinkAdresses' in usage data. One example app is the built-in CM12 browser.
I can still see old behavior though like UID 1000 does 'clients3.google.com' resolving with the old API.

**Comment by M66B** [comment]
If there is usage data for the function, then the restriction works and I don't see any reason to look into this, considering that the restriction for the corresponding new Lollipop function also seems to work. Things are simply different on Lollipop.

**Comment by BlueMax** [comment]
> If there is usage data for the function, then the restriction works
That's the question... the 'LinkProperties.getLinkAdresses' (even though it does have usage data indeed) only gets called once and only once (not per dns request). There is also no additional usage data like value/parameter (that usually shows the requested address) that would prove the DNS requests are done by this API now. 
I can clearly see an increased amount of blocked IPs in AFWall/iptables log that is a result of not blocked DNS request that has been handled by XPrivacy before. This happens even though 'LinkProperties.getLinkAdresses' is blocked.

I don't call it a bug. It rather looks like the apps do their DNS requests by some API XPrivacy doesn't cover yet.

**Comment by M66B** [comment]
Another remark: it is not the goal of XPrivacy to prevent DNS resolving. Restricting access to IP addresses is a feature because IP addresses can be used as identification.

What I like to see is an application which has access to your IP address despite restricting it with XPrivacy.

**Comment by BlueMax** [comment]
Ok, then everything's fine.
