### ISSUE TITLE
On demand for storage 

### ISSUE THREAD

**Issue by J316** [M66B/XPrivacy#2157]
Often the on demand function doesn't work for storage category, allowing or denying as it's set.

**Comment by M66B** [comment]
Isn't this the problem documented in the limitations section? If you mean your choice is not set, which is unlikely, please provide a small as possible logcat with XPrivacy debug logging enabled.

**Comment by M66B** [comment]
Also, please describe the exact steps to reproduce.

**Comment by J316** [comment]
Looks like it's gone
