### ISSUE TITLE
no sound on outgoing or incoming calls [nexus4]

### ISSUE THREAD

**Issue by martini22** [M66B/XPrivacy#2158]
since the last two updates i can not hear the person i am calling and he can't hear me. Same for incoming calls. I can pick up the phone but can't hear anything and they can't hear me. sms works.
Xprivacy is the only module i use and disabling it in Xinstaller solves the issue, but then i feel naked :(
I am using cm11-20141219-nightly-mako from december 2014 and i think it worked up to version 3.6.0 flawlessly.

**Comment by M66B** [comment]
XPrivacy does nothing directly with sound, but maybe this is caused by a restriction, so check your usage data.
