### ISSUE TITLE
[Lollipop] IMEI not restricted

### ISSUE THREAD

**Issue by Droidphilev** [M66B/XPrivacy#2159]
I use CM12 (Temasek build) and it seems that apps like "device ID" (made by evozi) can read the real imei.

**Comment by dogmatism** [comment]
Same here.  CM12 with AK kernel

**Comment by M66B** [comment]
Please try the version from here: #2162

**Comment by M66B** [comment]
Will be fixed in the next release, but will result in bootloops in many cases, because of a bug in Xposed.
