### ISSUE TITLE
On demand timed reset

### ISSUE THREAD

**Issue by J316** [M66B/XPrivacy#2161]
Usually the on demand categories are to allow a particular permission for a specified time. But sometimes it happens to grant or deny an on demand permission permanently, but then the next time the on demand pop up appears the checkmark for the timer is unchecked, and if that happens while screen off or not looking at the display a permission can be permanently denied or allowed not knowing it happened. So why not adding the possibility to choose a default setting for the pop up so it resets every time to that template?

**Comment by M66B** [comment]
On demand timeout is always allow/deny once. Allow/deny is taken from the current restriction setting, which is by default allow, but can be set to default deny by applying a template, possible when installing an application.

**Comment by J316** [comment]
No, I don't mean that. You can allow/deny for 15 seconds, 1 minute, etc. But if you want to permanently allow/deny you uncheck the timed restriction. But if an on demand pop up shows while screen off or while not watching the display it will automatically allow/deby permanently without knowledge. So it would be useful if the next pop up will be set on 15 seconds anyway, even if the previous was unchecked. Or rather set on a template specified in settings. Not the template for the restrictions, but for the on demand pop up.

**Comment by Cerberus-tm** [comment]
@J316 Marcel said: "On demand timeout is always allow/deny once."
You seem to be saying this this is not true, that on-demand **time-out** may apply an allow or deny permanently. Are you positively sure?

**Comment by J316** [comment]
![1](https://cloud.githubusercontent.com/assets/8670476/6543683/17ac312a-c526-11e4-8e29-8d9b7e17a402.png)
You see the third checkmark "once for"? If I uncheck it then that restriction will be permanent, next time I won't be prompted. But the next pop up will have it unchecked too, so if it runs out of time I end up with a permanent allowed or denied restriction without knowing it. That's why the next pop up should have "once for" checked by default. I was thinking about a template for this pop up too.

**Comment by Cerberus-tm** [comment]
Marcel says the restriction will **not** be permanent if the pop-up times out, **regardless of the check mark**. Are you saying that is not true? I haven't really tested it myself.

**Comment by J316** [comment]
If it's not "once for" it's "once", meaning the question mark disappears from the app settings and next time it will be allowed/denied.

**Comment by Cerberus-tm** [comment]
I don't understand. Are you saying what I said was not true, or are you saying something else?

**Comment by J316** [comment]
Give it a try by yourself and you will understand clearly.

**Comment by Cerberus-tm** [comment]
You still haven't told me whether you think my paraphrase of Marcel is not correct (which means there is a bug) or not. So I don't know what to test.

**Comment by J316** [comment]
It's not a bug, it's a not so smart working way. It's an enhancement I'm proposing

**Comment by Cerberus-tm** [comment]
Still no yes or no...

**Comment by J316** [comment]
Marcel didn't understand what I said

**Comment by Cerberus-tm** [comment]
I give up, but I wish you good luck.

**Comment by M66B** [comment]
The result of unattended on demand popups is never stored permanently, but are always once for 15 second, regardless any setting.
