### ISSUE TITLE
Make Xprivacy Android Studio compatible, styles.xml

### ISSUE THREAD

**Issue by amakuramio** [M66B/XPrivacy#2163]
This saves unneeded files by calling the java libraries from the application itself and maybe fix the hook bug somewhat

project.properties (edit) 

```
android.library.reference.1=../../appdata/local/android/sdk/extras/android/m2repository/com/android/support/appcompat-v7
android.library.reference.2=../../appdata/local/android/sdk/extras/android/m2repository/com/android/support/cardview-v7
```

>this makes the project able to be imported with android studio

the  dependencies of build.gradle (xprivacymain on android studio)
add 

```
 dependencies
            {
                compile fileTree(dir: 'libs', include: ['*.jar'])
                compile 'com.android.support:cardview-v7:+'
                compile 'com.android.support:recyclerview-v7:+'
            }
```

or

```
dependencies {
    compile project(':appcompatv7')
    compile project(':cardviewv7')
}
```
but then a styles.xml error occurs. 
adding <resources xmlns:android="http://schemas.android.com/apk/res/android"> in the heading solves the problem a bit but then it says the file has an invalid ending even if if added </resources>

**Comment by M66B** [comment]
I am not using Android Studio, so I cannot do this.
In the tools directory there are instructions and an outdated build.gradle for Android Studio.
Maybe they are useful to you and maybe you can update these files.

**Comment by amakuramio** [comment]
because it was old... OK, I will do my best to make this project support android studio, and if I may succeed, will do a pull request
