### ISSUE TITLE
WhatsApp not listed in XPrivacy app list

### ISSUE THREAD

**Issue by CardinalSin** [M66B/XPrivacy#2164]
Hi folks. Great app, thanks for all the work you've put in.
I just started using it today - version 3.6.2 (464) - and it's super.
But strangely the app list does not show WhatsApp. It does show all the rest, as far as I can tell.
Perhaps the devious programers at WhatsApp have found a way to knobble XPrivacy?

**Comment by M66B** [comment]
There is a FAQ about applications not shown, including solution.
