### ISSUE TITLE
Xprivacy and LuaJit memory space conflict

### ISSUE THREAD

**Issue by gerroon** [M66B/XPrivacy#2167]
Hi

I try use Koreader on my device and it has been crasing so the KR devs looked into it with my logs and they think that there is a memory space allocation issue. I am wondering if you could look into it if this is an Xprivacy issue problem or something to do with Luajit and Xprivacy not liking each other.

The bug listing is here
https://github.com/koreader/koreader/issues/1456

thanks

**Comment by M66B** [comment]
This is more probably caused by using XPrivacy alongside LBE Security Master of the security center of MIUI. See here for details: https://github.com/M66B/XPrivacy#compatibility

**Comment by gerroon** [comment]
@MB6B

Do you mind comment on the actual bug, so the the devs are aware of what they are looking into?

thanks

**Comment by gerroon** [comment]
Btw I do not know what LDE Security Master is, I do not have such and app. I am on CyanegonM 4.4.4

**Comment by M66B** [comment]
I am not going to look into this issue, since this problem is most likely caused by either Xposed or LuaJit and not by XPrivacy.

**Comment by gerroon** [comment]
M66B, thanks for your time.
