### ISSUE TITLE
failed to activate license

### ISSUE THREAD

**Issue by kapiljhajhria** [M66B/XPrivacy#2172]
so I followed all the methods or solutions described here. but nothing worked.
i got the license from email 
stuff that i did to activate license file for my device.

1. placed it in root folder sdcard/0 and rebooted- didn't work
2. placed it in /data/data/xprivacy folder and changed its permission to match the remaining files permission in that folder. rebooted - didn't work
3. name of the license file was XPrivacy_license.txt
4. opened it using es file explorer. i mean using es file explorer i opened it with xprivacy and rebooted
still didn't worked

i am fairly good with android so just let me know if there is anything else i can do?

**Comment by hateusingusername** [comment]
Use xprivacy pro licence fetcher https://play.google.com/store/apps/details?id=biz.bokhorst.xprivacy.license

**Comment by M66B** [comment]
Please reply to the pro license activation instructions for support.
