### ISSUE TITLE
On-demand dialogs when restrictions have been fetched

### ISSUE THREAD

**Issue by NTWarrior** [M66B/XPrivacy#2173]
Not sure if this is working as intended but although I have fetched crowd restrictions, I still get XPrivacy popups asking me about restrictions for those that should have been fetched. For example, I just got a popup regarding the Shell permission for Facebook Messenger; I assumed that it was still supposed to appear and the fetched restrictions affect what the timeout action will be but I see Messenger has a deny score of 56% for Shell but the timeout default was Allow.

I'm showing more ignorance here but does the "Don't Know" do whatever the timeout option is?

Stock Android 4.4.4
Xprivacy (pro) 3.6.2

**Comment by M66B** [comment]
Fetching restrictions doesn't enable/disable asking, so the previous setting will be used.

Don't know applies a reasonable default, like timeout.

Please ask your next question on the XPrivacy XDA forum.

https://github.com/M66B/XPrivacy#support

**Comment by NTWarrior** [comment]
Apologies. I posted here instead of XDA because I intended it as a request
for an option not to ask about restrictions if you've already fetched them,
if that wasn't already how it was supposed to be working.

**Comment by M66B** [comment]
Ask you question / describe your problem on XDA and I will answer / give a solution, which might be useful for more people.
