### ISSUE TITLE
Restrict access to battery and power consumption information

### ISSUE THREAD

**Issue by KOLANICH** [M66B/XPrivacy#2176]
http://arxiv.org/abs/1502.03182

**Comment by M66B** [comment]
Sorry, but this is far fetched and most probably not usable in reality.

**Comment by KOLANICH** [comment]
>Moreover, now almost 90% of the estimation errors are below 1 km (fig. 6).

**Comment by M66B** [comment]
I have read some stickers about this and comments about it and it is just "another" security research without any value. Show me an application which can show my position within 1 km, which cannot be restricted by XPrivacy and U will look into it. Note that information which can be restricted is needed to make it work anyway.

**Comment by KOLANICH** [comment]
>Note that information which can be restricted is needed to make it work anyway.

>Finally, we demonstrate that power measurements could be stable across different models of smartphones.
>This stability would allow an attacker to obtain a reference power measurement for a drive without using the same phone as the victim’s. We recorded power measurements, while transmitting packets over cellular, using two different smartphone models (Nexus 4 and Nexus 5) during the same ride, and >Table 3 indicates that for Nexus 4 #1 the combined route estimates were able to identify the ﬁnal road segment for 80% of scenarios. For Nexus 4 #2 which run many applications the ﬁnal destination estimates are somewhat less accurate (72%). This is attributed to the more noisy measurements of the aggregate power consumption. The accuracy for the two models – Nexus 5 and HTC Desire – are lower than the accuracy achieved for Nexus 4. Remember that all our pre-recordings were done using a Nexus 4.we aligned the power samples, according to absolute time.

>Show me the app
Contact the article authors for that.

**Comment by M66B** [comment]
"To locate the phone, we assume the attacker has prior knowledge of the area or routes through which the victim is traveling."

Restricting location will render this method useless, since it needs a base location to start.

**Comment by M66B** [comment]
"*Contact the article authors for that.*"

XPrivacy is a community project, so I expect effort from the community as well, which is not only requesting features and asking questions.

**Comment by KOLANICH** [comment]
>"To locate the phone, we assume the attacker has prior knowledge of the area or routes through which the victim is traveling."
This means that the area is known so they can drive it with their equipment (or equipment of users of controlled apps) and measure power consumption on routes of that arrea.

**Comment by Cerberus-tm** [comment]
It would still be extremely difficult, if not impossible, to get your location from this in practice. They would have to map all possible routes around the city, which soon becomes an almost-infinite number. If you have applications running on your phone that use the battery, it all falls apart. Etc.

While it would be nice to still be able to block this potential method, I can completely understand why this has a low priority for Marcel. And giving him orders(!) is in my opinion inappropriate. Why don't we start by thanking him for the tremendous effort he has put into the great application that Xprivacy is now! I remember the days of LBE...

**Comment by KOLANICH** [comment]
>They would have to map all possible routes around the city

No. Read carefully. They only need all combinations of 2 sequential the pieces of routes.

>If you have applications running on your phone that use the battery, it all falls apart. Etc.

They state that ysing machine learning they have managed to solve this problem.

**Comment by eeeeeazy1** [comment]
STOP SENDING ME E-MAILS!

**Comment by M66B** [comment]
@eeeeeazy1 GitHub will send you notifications if you have chosen to follow a project or if you create/commented on an issue. I don't see comments of you here, so I guess you have chosen to follow this project. So, modify your GitHub settings to stop receiving notifications.

To be very clear, nobody is sending you unsolicited message, you have enabled this yourself.

**Comment by eeeeeazy1** [comment]
IT WAS NOT ME!

**Comment by M66B** [comment]
It was absolutely you.
Maybe it is because you have starred the project:
https://github.com/eeeeeazy1?tab=activity

**Comment by eeeeeazy1** [comment]
It was not me...maybe the girl friend, but I assure you ....IT WAS NOT ME!

**Comment by M66B** [comment]
Anyway, you will now get any message written in this issue, since you are participating, which you did yourself by writing here ...

**Comment by eeeeeazy1** [comment]
GET A LIFE!
