### ISSUE TITLE
Can't mount MTP

### ISSUE THREAD

**Issue by J316** [M66B/XPrivacy#2180]
My computer can't mount the phone as MTP either in Linux or Windows, unless I disable XPrivacy. But the only system apps with storage restricted are GApps, dialer, DSP manager and contacts storage, so nothing really related with it apparently. Also, in usage data it's not showing anywhere as blocked. So why doesn't it work? What is the permission to unrestrict to make it work without disabling the whole XPrivacy?

**Comment by M66B** [comment]
Questions should be ask in the XDA forum, so that others can benefit from the answers as well.
https://github.com/M66B/XPrivacy#support

This problem is caused by a dangerous restriction without usage data.
