### ISSUE TITLE
Menus overlapping issue

### ISSUE THREAD

**Issue by SWADED** [M66B/XPrivacy#2182]
http://forum.xda-developers.com/showpost.php?p=60407063&postcount=14616

**Comment by M66B** [comment]
Please let me know if this version improves things:
https://crowd.xprivacy.eu/XPrivacy_3.6.9-1.apk

I have upgraded the [Android support library](http://developer.android.com/tools/support-library/index.html) to version 22.1.0

**Comment by SWADED** [comment]
Fixed it!

**Comment by M66B** [comment]
Not really a surprise, but nice anyway!
