### ISSUE TITLE
it seems that 3.6.9 doesnt restrict (android system) app with cm 11 

### ISSUE THREAD

**Issue by ZEROZ90** [M66B/XPrivacy#2184]

**Comment by ZEROZ90** [comment]
i have tested with two different devices it isnt restricted all

**Comment by M66B** [comment]
There is absolutely no difference in restricting user and system applications, so there is something else going on.

Please be more specific about which restrictions you apply to which application. With the information provided I cannot help.

**Comment by an0n981** [comment]
Same issue here. UID 1000 is not restricted, no usage data, debug log (https://gist.github.com/an0n981/541f3cdbd6906d091f16) does not contain any entries

**Comment by M66B** [comment]
Which restriction(s) should I look into?
To be sure: restricting system components was enabled?

**Comment by an0n981** [comment]
Nothing is restricted for UID 1000, as well as no usage data. Restrict system components is checked, all other system components are properly restricted. Last known working version for me was 3.6 (haven't updated in a while). Also same issue verified on a Nexus 5 with Omni 4.4.4

**Comment by M66B** [comment]
I have checked, but only the identification category cannot be restricted for system components:
https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/PrivacyManager.java#L465

Maybe this is an issue of recent Xposed version.

**Comment by an0n981** [comment]
I have downgraded to 3.6.2 then updated 3.5, 3.6.6.1, 3.9. The only version where UID 1000 is not restricted with no usage data is 3.6.9.
I am also still using XPosed 2.6.1 from May 2014.
Could [this commit] (https://github.com/M66B/XPrivacy/commit/d79be6976f51acf62a4bc7c521f10436804c3bd2) be the reason?

**Comment by M66B** [comment]
Maybe it is, I will check for the next release.

**Comment by M66B** [comment]
@an0n981 this will be fixed in the next release.

Please note that the fix is for another problem as this issue was originally about.
Android system components are not the same as system applications.

**Comment by M66B** [comment]
@an0n981 see this issue for a new version: https://github.com/M66B/XPrivacy/issues/2162

**Comment by an0n981** [comment]
I confirm that the issue is resolved
