### ISSUE TITLE
FAQ (9) What is the procedure to update a ROM: leak private data?

### ISSUE THREAD

**Issue by powerman** [M66B/XPrivacy#2185]
Isn't with recommended steps private data like contacts may be read by any application between steps "8. Reboot to Android" and "10. Import XPrivacy settings"? Because of Flight more these apps won't be able to immediately send collected data by internet, but they can store that data and send it later (assuming these applications usually don't have access to contacts but allowed to access internet).

Isn't it's much more safe to delay step "3. Use the menu option in XPrivacy to clear all data." until before step "10. Import XPrivacy settings" (if it's needed at all - I assume importing will clear all data before import by default). Yeah, there is a chance some app will change UIDs and no/wrong rules will be applied to them, but if we just updating to _another version of same ROM_ this chance is low.

Or this FAQ item was meant about replacing ROM by some other, not just updating current ROM to newer version? If it's about replacing ROM by some other, then it's unusual to avoid data wipe in this case.

**Comment by M66B** [comment]
This is better discussed on the XDA forum:
http://forum.xda-developers.com/xposed/modules/xprivacy-ultimate-android-privacy-app-t2320783
