### ISSUE TITLE
Galaxy S5 Unable to see the entire Applist

### ISSUE THREAD

**Issue by Xprivecier** [M66B/XPrivacy#2187]
First, thank you M66B for creating this amazing platform and for your incredible work.

I have checked all the menus and explored every option to be lead to the conclusion I have an issue, maybe a bug) and hope to resolve it in this forum.
I have a rooted Galaxy S5 with model SM-G900T with Android Version 4.4.2
I have installed X-posed framework using as well as XPrivacy.

As you can see on the screen shot attached, my Galaxy is showing only 11 apps out of 226. no further scrolling down helps and there are further pages. I do see occasional pop up screens for apps that are not on the "11 chosen list", Like the google play app for example, proving me that they are recognized somewhere by Xprivacy. how can I access them on Xprivacy?

Thank You

![screenshot_2015-05-07-22-02-39](https://cloud.githubusercontent.com/assets/12315000/7529437/687e79e0-f506-11e4-823e-82304bc60229.jpg)

**Comment by M66B** [comment]
See here:
https://github.com/M66B/XPrivacy#FAQ74

And please read this:
https://github.com/M66B/XPrivacy#support
