### ISSUE TITLE
Device ID not randomized when setting up new MS Exchange ActiveSync Account

### ISSUE THREAD

**Issue by uywmxzsu** [M66B/XPrivacy#2188]
Hi all,

Device ID is not being randomized when I go to set up a new MS Exchange Account

Settings -> Accounts -> Add Account -> MS Exchange ActiveSync Account -> Manual Setup

The resultant Device ID shown at the 'bottom' of the screen is never 'randomized' no matter what I try
It displays SEC1.....03

I have set as 'active' in XPrivacy:  Email, Exchange Services, Google Services Framework

I installed GetID and when set as 'active' in XPrivacy it correctly randomizes the Device ID for GetID

However it is NOT randomizing for MS Exchange ActiveSync Account

- Samsung Galaxy S4
- Android v4.2.2
- XPrivacy v1.11.8

Any help is greatly appreciated :))

Thanks

**Comment by M66B** [comment]
If it works for GetID, it works for any application.
You'll need to find the right appliction to restrict.
Your best bet is to ask for help on the XDA forum.
http://forum.xda-developers.com/xposed/modules/xprivacy-ultimate-android-privacy-app-t2320783

**Comment by uywmxzsu** [comment]
The 'MS Exchange ActiveSync Account' is a standard App for all Android users

I assume if I am having this issue it is the same for everyone else

Just because it randomizes for GetID does not mean it is not a bug

Thanks M66B for palming off an issue question to another forum

Great way to foster community support .... NOT

**Comment by M66B** [comment]
Actually community support is better in the XDA forum than here ...

**Comment by M66B** [comment]
Another reason is that I cannot give you an answer to this question (it is not a bug), because I don't use ActiveSync.

**Comment by uywmxzsu** [comment]
Thanks M66B

Your a legend!!

It was the application 'caching' the Device ID - clearing the app data fixed the issue

For anyone who has the same issue, the 2 apps that generate the Device ID for MS Exchange ActiveSync Account are (Email, Google Services Framework)

Use XPrivacy to randomise those 2 apps, then clear the 'data' for 'Email', then restart Email

Device ID is now changed
