### ISSUE TITLE
No-ask function restrictions should override later category restrictions

### ISSUE THREAD

**Issue by jimbo1qaz** [M66B/XPrivacy#2189]
I disable user-agent manipulation and prompt for all other View operations.
When I approve an app's View operation, it overrides my user-agent "deny-without-prompt" and instead allows user agent manipulation.
Can you add an option for non-prompting function restrictions to be preserved when whole-category restrictions are applied?
You will also need an option for whole-category restrictions to overwrite no-ask function restrictions, much like resetting the category.

**Comment by M66B** [comment]
Function restrictions are exceptions to category restrictions, so the category restriction sometimes needs to be changed when answering on demand function restrictions. In other words: this cannot be changed.

**Comment by jimbo1qaz** [comment]
Do you have any valid reasons it can't be made optional?
