### ISSUE TITLE
Ask for code help

### ISSUE THREAD

**Issue by simper7** [M66B/XPrivacy#2190]
I'm a freshman of java. Now don't konw how to writing strict fake device(such as Imei,icci,,etc..) xposed  module. 
I'm leaving my email address. Can you say hi to my email, then i'll send you my development intention and code to you for help. Thx!
k7simper@126.com

**Comment by M66B** [comment]
I am sorry, but I have no time to help you to learn how to develop software.

**Comment by simper7** [comment]
Many thanks for your reply. I donated for a Xprivacy Pro, but unfortunately the App can't solve  my intention efficiently.  I tried to write fake code by myself, but seems can't finish by a freshman and failed. I need to sort the issue out very urgent. Think it's easy job to you to writing fake code but difficult for me, so i try to send the code to you and ask for your help. It's appreciate if possible receiving your help.
