### ISSUE TITLE
[bug] App can access sensors despite restricting them in XPrivacy

### ISSUE THREAD

**Issue by danielmmmm** [M66B/XPrivacy#2191]
Hei Marcel,

from the latest Humble Bundle I got "Tilt to Live 2: Redonkulous" and I was surprised that I can control the game using my phone's orientation, even though the whole sensor category is set to "deny".
My Motorola Droid 4 is running CyanogenMod 11 M12 and XPrivacy 3.6.9. The app in question does not have root access.

I made a LogCat right before starting the game and playing for a short time:
https://gist.github.com/danielmmmm/57994c0116fd8fb06f36

**Comment by M66B** [comment]
Can you post a link to the application?

**Comment by danielmmmm** [comment]
Unfortunately it is only available as a paid app (https://play.google.com/store/apps/details?id=com.onemanleft.tilttolive2&hl=en).
If you think this is something serious, then I can buy you the latest Humble Mobile Bundle as a gift (https://www.humblebundle.com/mobile). Either the cheapest option, which includes the game in question, or the 4 USD option, in case you are interested in the other games (for your own amusement, not to test them against XPrivacy ;-).

**Comment by M66B** [comment]
I never play games, but thanks for the offer.
Maybe you can find a free application with the same problem.

**Comment by danielmmmm** [comment]
Well, just buying that game is 1 USD. I would be fine with that.

**Comment by danielmmmm** [comment]
I just sent you a link to redeem the game to your address at faircode.eu.
Hope you manage to reproduce the behaviour that I described. If not, I hope I can help you otherwise ...

**Comment by M66B** [comment]
I have received the gift, but I have problems sharing my Google+ information (quite intrusive in this case).

Could you please check the usage data for sensor access (not only for the game itself) ?
The sensor restrictions are marked unsafe, since the hooks are applied in user space and can thus be unhooked.

**Comment by danielmmmm** [comment]
Oh, I don't remember Humble Bundle being so difficult/privacy intruding.

Anyways, sensor restrictions are not showing up in the XPrivacy usage data while running the game. Wouldn't sensors still show up if an app used native libraries? And what do native libraries "look like"? The app is allowed to load "main", but nothing else.

**Comment by M66B** [comment]
In theory native libraries could be used to access the sensor directly, but it is not likely this will be done, because it would be difficult to support all devices.

I will close this issue, since I have no means to look into this.
If you find a free application with this same problem, please feel free to comment again.

**Comment by danielmmmm** [comment]
Strange ... it is unlikely that I will encounter another app that does this, but I will report it if I do.
(Did you claim the Humble Bundle? If not, I could claim it and upload the app for you ... but that is just a suggestion...)

**Comment by M66B** [comment]
Yes, I claimed Humble Bundle, but installing the game was the problem.

**Comment by danielmmmm** [comment]
And it refused to run without Google+? I don't think I even have Google+ on my phone :-)
Well, I will report when/if I find another app.
