### ISSUE TITLE
Request: Set custom SERIAL

### ISSUE THREAD

**Issue by jack980517** [M66B/XPrivacy#2192]
I need to fake a specific SERIAL number for an app, but in "Limitations" it says SERIAL is initialized at boot and cannot be customized. But if so how can you randomize it?
I only need temporary change of the serial number, is it possible to set a serial number and enable it only for the next boot?

**Comment by M66B** [comment]
Question should be asked on the XDA forum, so others can benefit from the answers as well:
https://github.com/M66B/XPrivacy#support

**Comment by jack980517** [comment]
There is currently no way to set custom SERIAL in XPrivacy, so I think this should be considered a function request...

**Comment by M66B** [comment]
The number can be set using the settings.
