### ISSUE TITLE
security breach 4.x 3.6.9 (stable)

### ISSUE THREAD

**Issue by amakuramio** [M66B/XPrivacy#2196]
The app device id can still see all unfaked data  and xprivacy does not even detect it.

**Comment by M66B** [comment]
How did you check this?
As said on XDA I don't believe this is an issue.

**Comment by M66B** [comment]
Please test again with 3.6.10 and comment again if you still have this problem.

**Comment by amakuramio** [comment]
3.6.10 causes bootloop on 4.3 android.os.deadobjectexception

E/DisplayManager( 7162): android.os.DeadObjectException

E/DisplayManager( 7162): 	at android.os.BinderProxy.transact(Native Method)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)

E/DisplayManager( 7162): 	at android.os.BinderProxy.transact(Native Method)

E/DisplayManager( 7162): 	at android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayInfo(IDisplayManager.java:346)

E/DisplayManager( 7162): 	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:121)

E/DisplayManager( 7162): 	at android.view.Display.updateDisplayInfoLocked(Display.java:585)

E/DisplayManager( 7162): 	at android.view.Display.getMetrics(Display.java:540)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.policy.quicksetting.QuickSettingPanel.setSingleLine(QuickSettingPanel.java:490)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:898)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(Native Method)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3245)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3214)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:438)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:508)

E/DisplayManager( 7162): 	at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:100)

E/DisplayManager( 7162): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2687)

E/DisplayManager( 7162): 	at android.app.ActivityThread.access$1700(ActivityThread.java:159)

E/DisplayManager( 7162): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)

E/DisplayManager( 7162): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/DisplayManager( 7162): 	at android.os.Looper.loop(Looper.java:176)

E/DisplayManager( 7162): 	at android.app.ActivityThread.main(ActivityThread.java:5419)

E/DisplayManager( 7162): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/DisplayManager( 7162): 	at java.lang.reflect.Method.invoke(Method.java:525)

E/DisplayManager( 7162): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)

E/DisplayManager( 7162): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

E/DisplayManager( 7162): 	at dalvik.system.NativeStart.main(Native Method)

E/DisplayManager( 7162): Could not get display information from display manager.

E/DisplayManager( 7162): android.os.DeadObjectException

E/DisplayManager( 7162): 	at android.os.BinderProxy.transact(Native Method)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)

E/DisplayManager( 7162): 	at android.os.BinderProxy.transact(Native Method)

E/DisplayManager( 7162): 	at android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayInfo(IDisplayManager.java:346)

E/DisplayManager( 7162): 	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:121)

E/DisplayManager( 7162): 	at android.view.Display.updateDisplayInfoLocked(Display.java:585)

E/DisplayManager( 7162): 	at android.view.Display.getMetrics(Display.java:540)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.policy.quicksetting.QuickSettingPanel.setViewWidth(QuickSettingPanel.java:324)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.policy.quicksetting.QuickSettingPanel.setSingleLine(QuickSettingPanel.java:510)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:898)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(Native Method)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3245)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3214)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:438)

E/DisplayManager( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:508)

E/DisplayManager( 7162): 	at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:100)

E/DisplayManager( 7162): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2687)

E/DisplayManager( 7162): 	at android.app.ActivityThread.access$1700(ActivityThread.java:159)

E/DisplayManager( 7162): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)

E/DisplayManager( 7162): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/DisplayManager( 7162): 	at android.os.Looper.loop(Looper.java:176)

E/DisplayManager( 7162): 	at android.app.ActivityThread.main(ActivityThread.java:5419)

E/DisplayManager( 7162): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/DisplayManager( 7162): 	at java.lang.reflect.Method.invoke(Method.java:525)

E/DisplayManager( 7162): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)

E/DisplayManager( 7162): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)

E/DisplayManager( 7162): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

E/DisplayManager( 7162): 	at dalvik.system.NativeStart.main(Native Method)

D/STATUSBAR-QuickSettingPanel( 7162): setSingleLine:true

E/DatabaseUtils( 7219): Writing exception to parcel

E/DatabaseUtils( 7219): java.lang.SecurityException: Failed calling activity manager

E/DatabaseUtils( 7219): 	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2041)

E/DatabaseUtils( 7219): 	at com.android.providers.settings.SettingsProvider.callFromPackage(SettingsProvider.java:607)

E/DatabaseUtils( 7219): 	at android.content.ContentProvider$Transport.call(ContentProvider.java:279)

E/DatabaseUtils( 7219): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:273)

E/DatabaseUtils( 7219): 	at android.os.Binder.execTransact(Binder.java:388)

E/DatabaseUtils( 7219): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/DatabaseUtils( 7219): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)

E/DatabaseUtils( 7219): 	at android.os.Binder.execTransact(Native Method)

E/DatabaseUtils( 7219): 	at dalvik.system.NativeStart.run(Native Method)

E/DatabaseUtils( 7219): Caused by: android.os.DeadObjectException

E/DatabaseUtils( 7219): 	at android.os.BinderProxy.transact(Native Method)

E/DatabaseUtils( 7219): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/DatabaseUtils( 7219): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)

E/DatabaseUtils( 7219): 	at android.os.BinderProxy.transact(Native Method)

E/DatabaseUtils( 7219): 	at android.app.ActivityManagerProxy.handleIncomingUser(ActivityManagerNative.java:3407)

E/DatabaseUtils( 7219): 	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2038)

E/DatabaseUtils( 7219): 	... 8 more

D/AndroidRuntime( 7162): Shutting down VM

W/dalvikvm( 7162): threadid=1: thread exiting with uncaught exception (group=0x41977730)

I/Process ( 7162): Sending signal. PID: 7162 SIG: 9

E/AndroidRuntime( 7162): FATAL EXCEPTION: main

E/AndroidRuntime( 7162): java.lang.RuntimeException: Unable to create service com.android.systemui.SystemUIService: java.lang.SecurityException: Failed calling activity manager

E/AndroidRuntime( 7162): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2697)

E/AndroidRuntime( 7162): 	at android.app.ActivityThread.access$1700(ActivityThread.java:159)

E/AndroidRuntime( 7162): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)

E/AndroidRuntime( 7162): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/AndroidRuntime( 7162): 	at android.os.Looper.loop(Looper.java:176)

E/AndroidRuntime( 7162): 	at android.app.ActivityThread.main(ActivityThread.java:5419)

E/AndroidRuntime( 7162): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime( 7162): 	at java.lang.reflect.Method.invoke(Method.java:525)

E/AndroidRuntime( 7162): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)

E/AndroidRuntime( 7162): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)

E/AndroidRuntime( 7162): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

E/AndroidRuntime( 7162): 	at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime( 7162): Caused by: java.lang.SecurityException: Failed calling activity manager

E/AndroidRuntime( 7162): 	at android.os.Parcel.readException(Parcel.java:1431)

E/AndroidRuntime( 7162): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)

E/AndroidRuntime( 7162): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)

E/AndroidRuntime( 7162): 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:602)

E/AndroidRuntime( 7162): 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:934)

E/AndroidRuntime( 7162): 	at android.provider.Settings$System.getStringForUser(Settings.java:1162)

E/AndroidRuntime( 7162): 	at android.provider.Settings$System.getIntForUser(Settings.java:1266)

E/AndroidRuntime( 7162): 	at com.android.systemui.statusbar.policy.quicksetting.QuickSettingPanel.update(QuickSettingPanel.java:143)

E/AndroidRuntime( 7162): 	at com.android.systemui.statusbar.policy.quicksetting.QuickSettingPanel.setViewWidth(QuickSettingPanel.java:343)

E/AndroidRuntime( 7162): 	at com.android.systemui.statusbar.policy.quicksetting.QuickSettingPanel.setSingleLine(QuickSettingPanel.java:510)

E/AndroidRuntime( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:898)

E/AndroidRuntime( 7162): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/AndroidRuntime( 7162): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)

E/AndroidRuntime( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(Native Method)

E/AndroidRuntime( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3245)

E/AndroidRuntime( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3214)

E/AndroidRuntime( 7162): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:438)

E/AndroidRuntime( 7162): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:508)

E/AndroidRuntime( 7162): 	at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:100)

E/AndroidRuntime( 7162): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2687)

E/AndroidRuntime( 7162): 	... 11 more

E/AndroidRuntime( 7162): Error reporting crash

E/AndroidRuntime( 7162): android.os.DeadObjectException

E/AndroidRuntime( 7162): 	at android.os.BinderProxy.transact(Native Method)

E/AndroidRuntime( 7162): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

E/AndroidRuntime( 7162): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)

E/AndroidRuntime( 7162): 	at android.os.BinderProxy.transact(Native Method)

E/AndroidRuntime( 7162): 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:3718)

E/AndroidRuntime( 7162): 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:138)

E/AndroidRuntime( 7162): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)

E/AndroidRuntime( 7162): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

E/AndroidRuntime( 7162): 	at dalvik.system.NativeStart.main(Native Method)

E/installd( 1988): eof

E/installd( 1988): failed to read size

I/installd( 1988): closing connection

D/dalvikvm( 7219): GC_CONCURRENT freed 947K, 16% free 13696K/16264K, paused 1ms+1ms, total 21ms

I/Zygote  ( 6618): Exit zygote because system server (6957) has terminated

**Comment by M66B** [comment]
This is caused by an earlier problem not in de log.

**Comment by amakuramio** [comment]
I disabled xposed through recovery, using appdowngrader to downgrade to 3.6.9 and all is fine! 

Here is the security breach I'm talking about.

![not](https://cloud.githubusercontent.com/assets/6065170/7783537/a6e59d22-0180-11e5-84fa-0891562b803f.jpg)
![did](https://cloud.githubusercontent.com/assets/6065170/7783539/ac0ff626-0180-11e5-80f8-2d5384259ebd.jpg)

**Comment by amakuramio** [comment]
I got the other permissions working but only the device id part is still not spoofed :(

**Comment by amakuramio** [comment]
never mind, I got them working
