### ISSUE TITLE
Not work on HTC M7 5.0.2

### ISSUE THREAD

**Issue by PikuZheng** [M66B/XPrivacy#2199]
Hi, I'm using HTC M7 with Android 5.0.2. With XPrivacy 3.6.10, It

**Comment by PikuZheng** [comment]
It always shows XPrivacy is not activity in Xposed. I've already checked XPrivacy in Xposed and restart my phone. I'm using XPosed 3.0 alpha 2. Any idea?

**Comment by M66B** [comment]
http://forum.xda-developers.com/showpost.php?p=60928841&postcount=15108
