### ISSUE TITLE
IMEI not restricted on Lollipop #2

### ISSUE THREAD

**Issue by OrpheeGT** [M66B/XPrivacy#2200]
XPrivacy: 3.6.12
Android: 5.0.2 (SDK 21)

Brand: oneplus
Manufacturer: OnePlus
Model: A0001
Product: bacon
Device: A0001
Host: cyanogenmod
Display: LRX22G
Id: LRX22G

Method not found hook=phone/Srv_getDeviceIdForPhone5 (com.android.internal.telephony.PhoneSubInfoController)
Method not found hook=phone/Srv_getNaiForSubscriber5 (com.android.internal.telephony.PhoneSubInfoController)

**Comment by M66B** [comment]
http://forum.xda-developers.com/showpost.php?p=60932610&postcount=15131
