### ISSUE TITLE
3.6.13 not restricting IMEI and Phone/Srv_GetLine1 (Maybe others) KitKat 4.4.4

### ISSUE THREAD

**Issue by an0n981** [M66B/XPrivacy#2202]
Debut log from boot: https://gist.github.com/an0n981/baabff418a6b2a436d4c
Debug log around app launch that gets info: https://gist.github.com/an0n981/a2e56722bfa5895f6a56

IMEI also issue verified through TASKER

**Comment by M66B** [comment]
Maybe related to #2201

**Comment by an0n981** [comment]
Confirm 3.6.16 fixes this

**Comment by M66B** [comment]
I did test this on my girlfriend's KitKat device :-)
