### ISSUE TITLE
XPrivacy without root ( Superuser permission should be taken as Greenfy to control device without root privileges)

### ISSUE THREAD

**Issue by dinesh321t** [M66B/XPrivacy#2204]
Dear Sir,

I am using Asus ZenFone 5 and this is my first Android device previously I am user of Windows 

After using ZenFone I hate Android OS due to all apps leaking my personal information but when I installed Xprivacy I feel now I am secure to data leaks 

Sir I want to requesting you please make Xprivaxy works without root privileges if this need please gives super user permission to control device without root privileges as Greenfy works well with super user 

Please make XPrivacy with superuser permission not root privileges for lollipop because it's to hard for normal people who don't know about this

Thank you for great development to make people secure and safe

Thank & Regards 
Dinesh Kumar

**Comment by M66B** [comment]
XPrivacy does not need root.
Xposed does require root, however.
Without root it is not possible to modify the behavior of Android.
