### ISSUE TITLE
No runing xprivacy on LG L90

### ISSUE THREAD

**Issue by smiledexter** [M66B/XPrivacy#2205]
No runing xprivacy on LG L90 (405n) andoid 5.0.2, Version 3.6.13 BETA Xprivacy

Xposed program xprivacy activated, but not runing xprivacy, writes "did you enable XPrivacy in the Xposed installer and reboot your device?"

Attach logcat from turning on the phone https://drive.google.com/file/d/0B8Ja1XWxA7b4RUhDUnZ1REY0LVU/view?pli=1

**Comment by M66B** [comment]
The first XPrivacy log line is:

```
W/XPrivacy( 3575): Hooking package=com.android.calendar
```

Which means Xposed seems to be running and that XPrivacy is enabled in Xposed.

What is missing is the call to initZygote (which takes care of starting the privacy service).

This could be an Xposed/XPrivacy problem or the logcat is not complete.

Did you capture the logcat from your PC starting before turning on your device?

**Comment by smiledexter** [comment]
mistake, sorry, xprivacy program shows "Privacy service version mismatch; did you reboot your device after upgrading XPrivacy?"

Logcat clear before turning off the device, and restart the device is loaded, when he showed xprivacy a message the capture Logcat.

**Comment by M66B** [comment]
Try turning your device off and on to make sure it is a full reboot.

**Comment by smiledexter** [comment]
lot together overload does not work, perhaps it Xposed error Because it starts the OS each time optimize apps, this one, by the way.

**Comment by smiledexter** [comment]
Tot together overload does not work, perhaps it Xposed error Because it starts the OS each time optimize apps, this one, by the way.

**Comment by M66B** [comment]
Given your remark about optimizing each time, I really think this is an Xposed problem.

**Comment by smiledexter** [comment]
Thanks
