### ISSUE TITLE
Bootloop on 3.6.16 and Kit Kat 4.4.2

### ISSUE THREAD

**Issue by OrpheeGT** [M66B/XPrivacy#2209]
Hello,

As discussed on XDA, I have a bootloop when I update to 3.6.16 on my Samsung Galaxy Tab S.

I don't know how to attach log on github, so there are here : http://d-h.st/gXdg

Thank you

**Comment by M66B** [comment]
Could you please try this version:
https://crowd.xprivacy.eu/XPrivacy_3.6.16-1.apk

**Comment by OrpheeGT** [comment]
it boot, but it says xprivacy need to reboot... And Of course I rebooted, twice

**Comment by an0n981** [comment]
Same issue here, privacy version mismatch. Restrictions were working

**Comment by M66B** [comment]
Since @an0n981 didn't have the reported problem (as far as I know), I like to know from @OrpheeGT if this version is working now:
https://crowd.xprivacy.eu/XPrivacy_3.6.16-2.apk

**Comment by OrpheeGT** [comment]
It boots, and Xprivacy is starting, but I had an error at start, mail sent as asked by the app.

XPrivacy: 3.6.16
Android: 4.4.2 (SDK 19)

Brand: samsung
Manufacturer: samsung
Model: SM-T805
Product: chagallltexx
Device: chagalllte
Host: SWDD3918
Display: KOT49H.T805XXU1ANH1
Id: KOT49H

com.android.server.am.ActivityManagerService.mContext not found
com.android.server.am.ActivityManagerService.mContext not found
com.android.server.am.ActivityManagerService.mContext not found
com.android.server.am.ActivityManagerService.mContext not found

**Comment by M66B** [comment]
@OrpheeGT you can ignore this message, it will be gone in the next release.

**Comment by M66B** [comment]
@an0n981 is your problem solved?

Version mismatch means that the Xposed part is a different version than the application part.
Try to disable and enable XPrivacy in Xposed and reboot after this.

**Comment by an0n981** [comment]
As you previously mentioned, I didn't have the original problem. I only tested the 6-1 update, where the version mismatch happened. If you think it might benefit, I can test the -2 update.

**Comment by M66B** [comment]
I am preparing a new release right now, so better try that.
