### ISSUE TITLE
Sim subscriber id not being spoofed 

### ISSUE THREAD

**Issue by Hobbsicle** [M66B/XPrivacy#2212]
Hi,

Android 5.1.1 using version 3.6.17 of xprivacy. 

Testing with the device id app (com.evozi.deviceid) shows everything works and is blocked or spoofed apart from the sim subscriber id, which shows my original id and isn't spoofed despite being blocked in xprivacy.

**Comment by M66B** [comment]
I have tested this on Android 5.1.1 before and it worked, but I will look into it again.

**Comment by M66B** [comment]
I have on stock Android 5.1.1: "*SIM Subscriber ID: Not Found*", so it works for me.
To be sure I have also tried this in XPrivacy compatibility mode with the same result.
What I cannot reproduce, I cannot fix, sorry.
