### ISSUE TITLE
compatibility mode despite aosp file on KK

### ISSUE THREAD

**Issue by Vankog** [M66B/XPrivacy#2213]
I am not sure about this, but I figure I just report it to be safe:

I am still on KitKat - non-stock ROM (However, the nvidia Shield ROM is quite near to stock).  I had been forcing AOSP mode successfully for several months. Now that this option is externalized to the existence of the /data/system/xprivacy/aosp file this does not get enforced any more. The file exists (was set by the app, not by me), but I in compatibility mode.

**Comment by M66B** [comment]
Why not read the changelog?

**Comment by Vankog** [comment]
@M66B : 
I did, that's why I told you I am on KitKat. The changelog states:
> Version 3.6.8 UNSUPPORTED:
> Running in compatibility mode on Lollipop
...
> Version 3.6.14 BETA
> Running XPrivacy in compatibility mode on Android 5.x, except for stock ROMs (issue)
...
> Version 3.6.16 BETA
> /data/system/xprivacy/aosp
> This file can be created/deleted by toggling the main setting AOSP mode

So what exactly do you mean?

**Comment by an0n981** [comment]
@Vankog you have to add this to build.prop: xprivacy.options=ignoreselinux

Version 3.6.16 BETA

Fixed crash on clear cache (flush) on Lollipop
Fixed translation of isolated process uids (debug info)
Reading property xprivacy.options=ignoreselinux from /system/build.prop to ignore SELinuxSettings this property enables reading of these files again, but might result in a bootloop for some:/data/system/xprivacy/disabled/data/system/xprivacy/aosp
This file can be created/deleted by toggling the main setting AOSP mode

**Comment by Vankog** [comment]
Thank you @an0n981! Did the trick. 
I always  thought the the whole SELinux stuff is only meant for Lollipop. That's why I never tried this.
