### ISSUE TITLE
Abnormal boot time (12 min!!)

### ISSUE THREAD

**Issue by Stunherald** [M66B/XPrivacy#2214]
Hiao ... i just re-flashed my Motorola Photon Q with the same CyanogenMOD 10.2.1 which i had before. I've installed the latest SuperSU (v2.46 , which i also had before). Then i've installed latest Xposed framework (58/54). Everything went fine till this point.

Then i've installed latest Xprivacy 3.6.17 available via Xposed and did couple of restarts ... i was facing boot times like 1:30 min (from motorola logo appears till sim PIN prompt.). I did not changed anything but last two restarts took 12min (!) ... not kidding, used stopwatch for the second one.

After disabling Xprivacy i had 22sec boot time.

Before the full re-flash i had a bit older version of Xprivacy - 3.6.9 which was working flawlessly before.

So, any ideas?

**Comment by M66B** [comment]
I don't have this problem.
Provide a logcat from boot and maybe we can tell what is going on.
I will close this issue for now, because without logcat I can do nothing.

**Comment by Stunherald** [comment]
Wow, thanks for swift reaction!

I just re-flashed everything from scratch (Kernel, ROM, gapps), will test again and let you know.
