### ISSUE TITLE
Reset during system freeze

### ISSUE THREAD

**Issue by CHEF-KOCH** [M66B/XPrivacy#2217]
This seems an pretty annoying bug during a system freeze because all Xprivacy settings will be reset to defaults after the next restart. I use the option to generate fake settings after each new start. This mostly takes some time and another Xposed addon called [Xposed Media Scanner optimizer](http://repo.xposed.info/module/com.thomashofmann.xposed.mediascanneroptimizer) which is also started at the same time as Xprivacy generates the new stuff. Maybe this is the problem.

Since this is difficult to reproduce there is no log or anything but imho there should be an option after a restart so that Xprivacy look at the last good saved settings and restore them automatically.

**Comment by M66B** [comment]
An automatic restore has two problems: your privacy is not automatically restored and the real problem is not solved.

**Comment by CHEF-KOCH** [comment]
Wouldn't you agree that restore most of all stuff is better as leave it entirely unprotected after the boot? E.g. if any installed AV crash the system or other freezes happens it remember the state/settings on the next boot, I expect such behavior from an app that claims to _secure_ something.

I not expect that Xprivacy fix possible freezes that are caused by other apps or the system but leaving this untouched or without any chance to get a notice is an security risk you just ignore.

**Comment by M66B** [comment]
I am not ignoring anything. There is not enough information about the real problem. XPrivacy will never reset/change restrictions on its own.

**Comment by CHEF-KOCH** [comment]
The problem isn't the system, there is currently no exception for such stuff implemented in Xprivacy - that's the point. If I code an example app which crash/freeze the system or Xprivacy the whole app would be useless and hacker/apps possible could execute xyz stuff which isn't proper restricted anymore, well it's a _maybe_ case but I see that very critical since there is no warning/promt or anything which shows that all settings are lost after the next restart (you must re-open the app to see that all is default). Of course we could use an backup, but that also needs a app/system restart + the fact that not everybody will save all changes each time (especially like me since I use a lot of apps). 

> your privacy is not automatically restored and the real problem is not solved.

That's not correct. The privacy you're talking about are only system apps or apps which have full access or boot complete permission implemented which are loaded right after or during the boot. By default Xprivacy not restrict any system critical components (and I also see no valid argument to do that) so that only applies to stuff which already was once executed + the boot permission. In fact such cases are rare. It's still better to have something restricted compared to nothing with no feedback that possible all user settings was lost.


I'll try to debug the stuff now but I think it have to do with the media-scanner and the fact that at the same time Xprivacy try to generate new stuff which may interference sometimes. But I don't think I'll find something since such case wasn't implemented/respected by Xprivacy.

**Comment by M66B** [comment]
Restrictions are never automatically removed, so I don't see how a crash/reboot will affect your privacy in a negative way.

**Comment by wbedard** [comment]
I'm not familiar with the details of the OP's issue but isn't it true that a crash/freeze of a device that results in corruption of XPrivacy;s database would, upon eventually restarting the device, result in all restrictions being automatically removed?  I seem to recall that this was the policy in the past but I am not aware if that has changed since then.

**Comment by M66B** [comment]
A corruption of the privacy database does happen, but very rarely. I have had less than a handful reports (using the debug info). Unfortunately Android has no tools installed to fix this and I see no ways to fix this. Creating a second database is not a real solution, because there is no way to know what is the right data. There is also a storage space and performance issue.

**Comment by wbedard** [comment]
Fortunately, I agree that it is a very rare occurrence (I've only experienced it once, myself).  If a user wanted to periodically backup their XPrivacy settings, to protect against any such a corruption, I can think of a couple of options currently available to them:

1. For XPrivacy Pro users, you could periodically "export" your XPrivacy settings and import them again upon learning of an XPrivacy database reset.  This has worked well for me in the past and it's a part of my current backup strategy for my Android devices.
2. For a less convenient option, a user could manually backup / restore the XPrivacy database from a custom recovery environment, which would include a stable copy of said database, assuming the the system performed a normal shutdown.

Any thoughts on either of these options?

**Comment by M66B** [comment]
Both options have as disadvantage you will go back in time, but I see no way to solve this. Importing/exporting is more selective than restoring a complete backup.

Data loss is always a problem and can only be prevented on hardware level. Android devices are not equipped to handle this and we have to learn to live with this.
