### ISSUE TITLE
BackPackTrack II has access to location without triggering location restriction request

### ISSUE THREAD

**Issue by an0n981** [M66B/XPrivacy#2219]

**Comment by M66B** [comment]
Which Android version?
Compatibility or AOSP mode?

**Comment by an0n981** [comment]
![screenshot_2015-06-12-08-54-23](https://cloud.githubusercontent.com/assets/6225554/8124968/753a3df8-10e1-11e5-9cf5-166490fd885a.png)

**Comment by M66B** [comment]
I have looked into this and it appears that requesting location updates by means of intents (this is what BP2 does, which is not very common) cannot be restricted in AOSP mode. I couldn't find the direct reason, but I am afraid the local location manager is handling the updates, which means this can only be solved by switching to compatibility mode.

I will investigate this further next week.

**Comment by M66B** [comment]
The location manager is not handling this locally:
http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.0_r1/android/location/LocationManager.java#LocationManager.requestLocationUpdates%28android.location.LocationRequest%2Candroid.location.LocationListener%2Candroid.os.Looper%2Candroid.app.PendingIntent%29
Investigating further ...

**Comment by M66B** [comment]
None of the location restrictions seem to work at all ...
