### ISSUE TITLE
Phone Freeze 5.1.1 (undocumented quirk)

### ISSUE THREAD

**Issue by an0n981** [M66B/XPrivacy#2220]
I have found a bug with 5.1.1 that causes the phone to hard freeze. If an app is open and the screen times out, it will cause a hard freeze if the app requests the onDemand documented in attached gist. Adding a black/whitelist entry manually via the db fixes the issue. I have tested this with WhatsApp and XDA Premium app.

https://gist.github.com/an0n981/69f79cf28a182210f8d5

(This may even be something that is ROM related and cannot be fixed in XPrivacy)

**Comment by M66B** [comment]
Apparently IntentFirewall is implemented differently in Android 5.1.1 causing this new problem. I have chosen to not support this (dangerous) feature, so you will have to workaround this problem yourself, sorry.
