### ISSUE TITLE
Upgrading system doesn't work

### ISSUE THREAD

**Issue by earth08** [M66B/XPrivacy#2221]
Dear Marcel,
Before some updates, when we uses to update app, there was an update process running soon after installing an update.
But now I can't find that, that update process is no more seen even after rebooting. 
I am on Yu Yureka with CM12os with 5.0.2

**Comment by M66B** [comment]
Works for me:

Update application:
```
W/XPrivacy( 7760): Package change action=android.intent.action.PACKAGE_REPLACED replacing=true uid=10312
```

Update service:
```
I/ActivityManager(  794): Start proc 3639:biz.bokhorst.xprivacy/u0a312 for broadcast biz.bokhorst.xprivacy/.BootReceiver
W/XPrivacy( 3639): Hooking package=biz.bokhorst.xprivacy
I/ActivityManager(  794): Start proc 3657:biz.bokhorst.xprivacy:update/u0a312 for service biz.bokhorst.xprivacy/.UpdateService
```

So, why do you think it doesn't work for you?
Note that the update service does nothing when there is nothing to update.
