### ISSUE TITLE
FR: Whois lookup 

### ISSUE THREAD

**Issue by gerroon** [M66B/XPrivacy#2223]
Hi

It would be very helpful if there is a way to send the url or the ip for a whois lookup from the block windows. When Xprivacy ask for permission  we generally do not have enough time and place to do this manually. So it would be nice at least if we could copy the ip address to clipboard if direct whois lookup is not possible.

thanks

**Comment by M66B** [comment]
I understand your wish, but technically this is not possible. It will result in system instability.

**Comment by gerroon** [comment]
At least maybe we can copy the ip to the clipboard?

**Comment by M66B** [comment]
Although I didn't try this (I did try network I/O from the on demand dialog), this would probably result in system instability as well. Also, the clipboard itself is intercepted by XPrivacy itself, which would be another complication.
