### ISSUE TITLE
Android permission icon (green key) is shown everywhere

### ISSUE THREAD

**Issue by 7astro** [M66B/XPrivacy#2226]
Just installed the recent XPrivacy version 3.6.19/3.6.9 (481) from Xposed repository with a pro license to notice the following strange behaviour: upon opening Xprivacy and clicking on any app - every category and every individual function/permission is displayed with a green key attached to it. Naturally, the expected behaviour would be to see those keys only attached to specific functions/permissions of an app. 

Prior to this XPrivacy install I had a non-pro version running from earlier this year, which didn't have this issue. The default filter of that version, if I recall correctly, wasn't set to "Filter on permission", which I think is where the problem partially resides. Because, if one unchecks this filter, then XPrivacy behaves as expected - keys are shown correctly upon viewing an app. 

The issue is reoccurring upon application of the mentioned filter and persists upon restarting app/device. 

Device: 4.4.2 (stock TouchWiz) with no "similar solutions" installed

**Comment by M66B** [comment]
The green key means an application has permission to use the function or needs no permission to use the function. The green keys are correct, else there would have been massive complaints.

**Comment by M66B** [comment]
If you have questions about the green keys, please use the XDA forum.

**Comment by 7astro** [comment]
True, my bad
