### ISSUE TITLE
Storage Category Permission indicator

### ISSUE THREAD

**Issue by an0n981** [M66B/XPrivacy#2229]
The storage category does not show the permission indicator if one of the 'new' (openAssetFile, oPenAssetFileDescriptor...) storage functions needs access, only if one of the 'original' (sdcard, media...)functions need access

**Comment by M66B** [comment]
For the mention functions are no Android permissions required ...

https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/Meta.java#L448

Or maybe I do understand what is being ment?

**Comment by an0n981** [comment]
What I mean is that the green key (1) only shows up if one of the original functions (2) (before you added the additional functions) needs access. This becomes an issue when users restrict the entire category based on the (lack of) green key
![screenshot_2015-07-07-17-11-49](https://cloud.githubusercontent.com/assets/6225554/8549628/1a59a870-24cc-11e5-94cc-c7f41a9389f3.png)

**Comment by M66B** [comment]
The appearance of the green key (=has Android permission) is independent of function usage (yellow triangle). The category green key is based on the function green keys or said differently, the green keys are configured per function in Meta.java. So, I still don't understand the problem I guess.

**Comment by an0n981** [comment]
I was teaching a new user about XPrivacy today and explained to him that if the category has a green key than at least one of the functions needs access, which is then indicated by a green key when the category is expanded. (Is this correct?) The storage category doesn't always follow this logic. From what I could gather the category key only shows up if one of the 'original' functions needs access.

**Comment by M66B** [comment]
"*Is this correct?*": yes

There are really no exceptions for old and new functions in Meta.java.

And also not while evaluating permissions:
https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/PrivacyManager.java#L1387

**Comment by an0n981** [comment]
Then I have at least 40 apps on my phone where this is displayed incorrectly. Also if I filter on permission and storage category those apps are not shown in the app overview

**Comment by wbedard** [comment]
From what I can see, if an app doesn't register the "sdcard" storage function, then the Storage category for that app will not have a green permissions key beside it.  This will be the case even if all other functions within the Storage category are registered by the app and have green keys displayed besides them.

**Comment by M66B** [comment]
Thinking again, this behavior is the intended behavior. Not requiring a permission is not a real permission, which is taken into account when filtering. Remember that XPrivacy does not use Android permissions other than for displaying things. In the beginning I even refused to do something with Android permissions.

**Comment by wbedard** [comment]
Given that XPrivacy is intended for all users expert and novice alike, could you provide some guidance (either here or in the FAQ) as to what a user should understand when they see a green key beside a function Category in XPrivacy.  Understanding that the "filter by permission" is functioning correctly, should they simply ignore how the categories themselves are displayed (with or without a key...) and always expand to the individual functions to understand what an app is needing?

**Comment by M66B** [comment]
Novice users should stick to category restrictions and expert user and in general more privacy minded users should look into function restrictions. Green key means has Android permission, which is always correctly reflected on category level, but has the issue as described here. Making everybody happy is difficult ...

**Comment by an0n981** [comment]
*Impossible

**Comment by wbedard** [comment]
Given the recent discussions on category restrictions vs regular/dangerous function restrictions and what novice vs expert users should fucus on, this guidance makes sense... thanks!
