### ISSUE TITLE
Restrincting IConnectivityManager:getDefaultProxy on LP causes java.lang.SecurityException

### ISSUE THREAD

**Issue by define** [M66B/XPrivacy#2233]
Please have a look - is it problem with Xposed or XPrivacy? 

Phone - HTC with LP version 5.1.
App *com.htc.zero* with uid **10101**.
Restricted IPC\Binder - **IConnectivityManager:getDefaultProxy**.

> Get service 10101/Binder(IConnectivityManager:getDefaultProxy;null) ipc=!restricted? (mcached) 0 ms
> Get client 10101/Binder(IConnectivityManager:getDefaultProxy;null) ipc=restricted 0 ms
> Restricting IConnectivityManager:getDefaultProxy code=35
> FATAL EXCEPTION: main
> Process: com.htc.zero, PID: 16270
> java.lang.SecurityException: XPrivacy
> 	at android.os.Parcel.readException(Parcel.java:1555)
> 	at android.os.Parcel.readException(Parcel.java:1508)
> 	at android.net.IConnectivityManager$Stub$Proxy.getDefaultProxy(
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java
> 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native 
> 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.
> 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
> 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:155)
> 	at android.app.ActivityThread.main(ActivityThread.java:5725)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at java.lang.reflect.Method.invoke(Method.java:372)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
> 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)

Full log http://pastebin.com/T1T6TE52

**Comment by M66B** [comment]
All IPC restrictions are handled by a security exception, so this is completely normal.
