### ISSUE TITLE
Shell Reboot Error

### ISSUE THREAD

**Issue by an0n981** [M66B/XPrivacy#2236]
My rom (Nameless 5.1.1) has 'random' reboots roughly every 6 hrs (I believe when GPS Xtra data is downloaded, I haven't a way to reproduce this at will yet). I am not sure if XPrivacy is actually the culprit, but even if not, I believe the E/XPrivacy errors are not a good sign.
Log:
https://gist.github.com/an0n981/194527e0d31162ddc8eb

**Comment by M66B** [comment]
The first moment I can look at this is Sunday. I have a bad mobile internet connection at this moment only. If you post a few error lines into this issue, I will take a look earlier.

**Comment by an0n981** [comment]
Here are the lines with E/XPrivacy:
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): android.os.DeadObjectException uid=1001
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): android.os.DeadObjectException
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at android.os.BinderProxy.transactNative(Native Method)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at android.os.BinderProxy.transact(Binder.java:496)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.ei.a(SourceFile:452)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.er.b(SourceFile:258)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:391)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:326)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:98)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:49)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.XLinkProperties.b(SourceFile:59)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at android.net.LinkProperties.getLinkAddresses(<Xposed>)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at android.net.LinkProperties.<init>(LinkProperties.java:100)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at android.net.NetworkAgent.sendLinkProperties(NetworkAgent.java:217)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at com.android.internal.telephony.dataconnection.DataConnection$DcDefaultState.processMessage(DataConnection.java:1257)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:967)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:790)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at android.os.Looper.loop(Looper.java:135)
07-17 17:23:44.276 E/XPrivacy/XLinkProperties( 5662): 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-17 17:23:44.276 I/XPrivacy/XLinkProperties( 5662): Get client 1001/LinkProperties.getLinkAddresses(null;null) internet=!restricted 17 ms
07-17 17:23:44.276 D/DcNetworkAgent1( 5662): NetworkAgent: NetworkAgent channel lost
07-17 17:23:44.281 D/DcNetworkAgent1( 5662): NetworkAgent: NetworkAgent channel lost
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): android.os.DeadObjectException uid=1001
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): android.os.DeadObjectException
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at android.os.BinderProxy.transactNative(Native Method)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at android.os.BinderProxy.transact(Binder.java:496)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.ei.a(SourceFile:452)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.er.b(SourceFile:258)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:391)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:326)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:98)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:49)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.XLinkProperties.b(SourceFile:59)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at android.net.LinkProperties.getLinkAddresses(<Xposed>)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at android.net.LinkProperties.<init>(LinkProperties.java:100)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at com.android.internal.telephony.dataconnection.DataConnection.getCopyLinkProperties(DataConnection.java:280)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at com.android.internal.telephony.dataconnection.DataConnection$DcDefaultState.processMessage(DataConnection.java:1169)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:967)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:790)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at android.os.Looper.loop(Looper.java:135)
07-17 17:23:44.281 E/XPrivacy/XLinkProperties( 5662): 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-17 17:23:44.281 I/XPrivacy/XLinkProperties( 5662): Get client 1001/LinkProperties.getLinkAddresses(null;null) internet=!restricted 2 ms
07-17 17:23:44.286 I/XPrivacy/XIoBridge(12203): Get client 10136/open(/storage/emulated/0/catlog/saved_logs/2015-07-17-16-53-33.txt;null) storage=!restricted (cached) 0 ms
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): android.os.DeadObjectException uid=1001
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): android.os.DeadObjectException
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at android.os.BinderProxy.transactNative(Native Method)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at android.os.BinderProxy.transact(Binder.java:496)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.ei.a(SourceFile:452)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.er.b(SourceFile:258)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:391)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:326)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:98)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:49)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.XInetAddress.b(SourceFile:75)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at java.net.InetAddress.getByAddress(<Xposed>)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at android.net.IpPrefix.toString(IpPrefix.java:194)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at android.net.RouteInfo.toString(RouteInfo.java:405)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at android.net.LinkProperties.toString(LinkProperties.java:571)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at java.lang.StringBuilder.append(StringBuilder.java:202)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at com.android.internal.telephony.dataconnection.DataConnection$DcDefaultState.processMessage(DataConnection.java:1170)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:967)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:790)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at android.os.Looper.loop(Looper.java:135)
07-17 17:23:44.291 E/XPrivacy/XInetAddress( 5662): 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-17 17:23:44.291 I/XPrivacy/XInetAddress( 5662): Get client 1001/InetAddress.getByAddress(null;null) internet=!restricted 9 ms
07-17 17:23:44.296 D/DcNetworkAgent1( 5662): NetworkAgent: NetworkAgent channel lost
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): android.os.DeadObjectException uid=1001
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): android.os.DeadObjectException
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at android.os.BinderProxy.transactNative(Native Method)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at android.os.BinderProxy.transact(Binder.java:496)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.ei.a(SourceFile:452)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.er.b(SourceFile:258)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:391)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:326)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:98)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:49)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.XInetAddress.b(SourceFile:75)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at java.net.InetAddress.getByAddress(<Xposed>)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at android.net.IpPrefix.toString(IpPrefix.java:194)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at android.net.RouteInfo.toString(RouteInfo.java:405)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at android.net.LinkProperties.toString(LinkProperties.java:571)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at java.lang.StringBuilder.append(StringBuilder.java:202)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at com.android.internal.telephony.dataconnection.DataConnection.toStringSimple(DataConnection.java:2148)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at com.android.internal.telephony.dataconnection.DataConnection.toString(DataConnection.java:2161)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at java.lang.StringBuilder.append(StringBuilder.java:202)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at com.android.internal.telephony.dataconnection.DataConnection$DcActiveState.processMessage(DataConnection.java:1809)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:967)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:790)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at android.os.Looper.loop(Looper.java:135)
07-17 17:23:44.301 E/XPrivacy/XInetAddress( 5662): 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-17 17:23:44.301 I/XPrivacy/XInetAddress( 5662): Get client 1001/InetAddress.getByAddress(null;null) internet=!restricted 5 ms
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): android.os.DeadObjectException uid=1001
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): android.os.DeadObjectException
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at android.os.BinderProxy.transactNative(Native Method)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at android.os.BinderProxy.transact(Binder.java:496)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at biz.bokhorst.xprivacy.ei.a(SourceFile:452)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at biz.bokhorst.xprivacy.er.b(SourceFile:258)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:391)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at biz.bokhorst.xprivacy.en.a(SourceFile:326)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:98)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at biz.bokhorst.xprivacy.XHook.c(SourceFile:49)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at biz.bokhorst.xprivacy.XNetworkInfo.b(SourceFile:55)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at android.net.NetworkInfo.getExtraInfo(<Xposed>)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at com.android.internal.telephony.dataconnection.DataConnection$DcActiveState.exit(DataConnection.java:1777)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at com.android.internal.util.StateMachine$SmHandler.invokeExitMethods(StateMachine.java:996)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at com.android.internal.util.StateMachine$SmHandler.performTransitions(StateMachine.java:852)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:800)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at android.os.Looper.loop(Looper.java:135)
07-17 17:23:44.311 E/XPrivacy/XNetworkInfo( 5662): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by M66B** [comment]
'*I believe the E/XPrivacy errors are not a good sign*': they are not a good sign, but also not the cause of your problem. *DeadObjectException* means a client detects a service died. You will have to find the cause for the services to die, which is also the cause/consequence of the reboots you are experiencing. Search for "FATAL" in the logcat. My best guess: Xposed is instable.
