### ISSUE TITLE
Add a saner default.

### ISSUE THREAD

**Issue by skorokithakis** [M66B/XPrivacy#2237]
Would it be possible to add a template that's a "saner" default? For example, I'm not sure if I should care about "IPC", "Identification", etc. Most of the time I care about contacts, location, and other personally identifiable data.

The current default is too restrictive, asking many questions every time I install a new app. Would it be possible to add a new template that I could use as the default, that would permit most of the harmless requests, like sensors, etc?

Equally good would be a writeup of how I could make such a template myself, if it exists, as I'm not sure which permissions are harmless and which are not, apart from the obvious ones like contacts access.

**Comment by M66B** [comment]
This is more a question than a feature request, so this is better discussed in the XDA XPrivacy forum.
