### ISSUE TITLE
hotornot gets real Location

### ISSUE THREAD

**Issue by MARAUDER-2** [M66B/XPrivacy#2238]
I restricted the Location for HotOrNot, but it still gets my real Location

It is free and available here:
https://play.google.com/store/apps/details?id=com.hotornot.app

**Comment by M66B** [comment]
This is too little information to work with.
Did you check the data usage of the application and of all application?
Did you restrict all location functions or only the location category?
Did you try to restrict the location for Play services? (be aware of any location caching).

**Comment by M66B** [comment]
Please read this:
https://github.com/M66B/XPrivacy#support
