### ISSUE TITLE
HTC 616 freezed

### ISSUE THREAD

**Issue by jpobeda** [M66B/XPrivacy#2239]
I succesfully installed Xposed 2.6.1 and XPrivacy 3.6.19 on my htc 616 following the instructions.

After enable XPrivacy and reboot my phone it takes less than a minute to get freezed and after a fews minutes the phone reboots itself.

Some boots I can open XPrivacy and see how it is loading and that´s all, nothing else happens.
When I disable XPrivacy module from Xposed it gets working fine again.

I uploaded 4 files by now, the one called xprivacy_logcat_filtered.txt (about 300 lines) is filtered by "xprivacy" took it from phone boot to crash on Android Studio.

Device: HTC Desire 616 dual sim
Android: 4.2.2
ROM: CyanogenMod Custom ROM http://forum.xda-developers.com/desire-616/general/xposed-intaller-htc-616-t3062211

https://mega.co.nz/#F!XwpllR4Q!81VFReKthpVhACooImNGoQ

**Comment by M66B** [comment]
The system server is crashing. This is probably not caused by XPrivacy, but more likely caused by an unstable Xposed version.
