### ISSUE TITLE
Version 3.6.18 and 3.6.19 hang device on boot

### ISSUE THREAD

**Issue by sputtene** [M66B/XPrivacy#2240]
After updating XPrivacy to version 3.6.19 (I don't know what version it was before) and rebooting, my device hangs during boot.

I didn't know what caused that (I didn't reboot for a long time, so I had no way to pinpoint what exactly caused it), so I reset my device to factory settings, wiping everything on the internal memory in the process.
I reinstalled all my apps, reinstalled Xposed and the Xprivacy module, version 3.6.19 (the latest at this moment).

When rebooting to activate Xposed and its modules, it progresses past the brand splash screen and hangs on the unlock screen (the one with the 3x3 circle grid), even before trying to connect to the cellular network.
It is also not responsive to touch events: I don't see a green line connecting the circles when I try to draw my unlock code.

When disabling Xposed by activating its safemode, then disabling XPrivacy by unticking its checkbox in the Modules list in the Xposed Installer, re-enabling Xposed and rebooting, my device boots normally.

No logs are generated in the Logs screen of the Xposed Installer when my device hangs, so I can't use that to pinpoint what is going wrong.

I tried uninstalling 3.6.19 and installing 3.6.18 instead and while rebooting, my device hangs in exactly the same way.
When I do the Xposed safeboot, disable XPrivacy, re-enable Xposed, reboot dance, my device boots normally again.

If there is any extra information I can provide, please let me know.

I'm using a Fairphone 1, which is quite stock AOSP (no heavy modifications).

**Comment by M66B** [comment]
Please provide a logcat. Search for "FATAL" in the logcat.
Without logcat there is little that can be done.

**Comment by sputtene** [comment]
When getting a logcat for both successful boot and unsuccessful boot, I noticed that even with XPrivacy disabled, I could get my device to hang.

If I disable Xposed, I can always boot successfully. If I enable Xposed, booting sometimes works and sometimes doesn't.

Closing the issue, because I don't think it's an XPrivacy bug.
