### ISSUE TITLE
Bootloop on 3.6.19 / i9505 LP5.0.1

### ISSUE THREAD

**Issue by tofkop** [M66B/XPrivacy#2242]
After getting Xposed to work on my stock deodexed rom, I get a bootloop after enabling the XPrivacy module. I tried another module without problem.

My logcat: http://pastebin.com/hwtmr573 (it's much longer but I think it's just repeating every boot)

Don't know if you need more information, or if you want me to try another version of XPrivacy?

**Comment by M66B** [comment]
Can you please find the part with 'FATAL' and post a few lines above it and some more below it? Most bootloops are caused by an unstable Xposed version.

**Comment by tofkop** [comment]
there's this one:
>07-30 11:06:27.907 D/SurfaceFlinger(  281): FPS : 12.03
>07-30 11:06:27.907 W/SurfaceFlinger(  281): Fail to Open /sys/devices/platform/gpusysfs/fps
>07-30 11:06:27.927 W/Zygote  ( 3837): Class not found for preloading: >com.android.okhttp.ConfigAwareConnectionPool$1
>07-30 11:06:27.947 E/art     ( 3837): Failed to register non-native method android.media.MediaRecorder.start()V as native
>07-30 11:06:27.947 F/art     ( 3837): art/runtime/jni_internal.cc:771] JNI **FatalError** called: RegisterNatives failed for 'android/media/MediaRecorder'; aborting...
>07-30 11:06:27.957 I/Zygote  ( 3837): !@prldclss1: 710 classes in 124ms.
>07-30 11:06:27.997 D/SurfaceFlinger(  281): FPS : 12.03
>07-30 11:06:27.997 W/SurfaceFlinger(  281): Fail to Open /sys/devices/platform/gpusysfs/fps

And

>07-30 11:06:28.027 I/Zygote  ( 3837): !@prldclssM: 1599 classes in 196ms.
>07-30 11:06:28.047 I/Zygote  ( 3837): Wait PC Thread 1=false 2=true
>07-30 11:06:28.057 F/libc    ( 3837): **Fatal** signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 4147 (Thread-11)
>07-30 11:06:28.067 I/Zygote  ( 3837): Wait PC Thread 1=false 2=true
>07-30 11:06:28.077 D/SurfaceFlinger(  281): FPS : 11.27
>07-30 11:06:28.077 W/SurfaceFlinger(  281): Fail to Open /sys/devices/platform/gpusysfs/fps
>07-30 11:06:28.087 I/Zygote  ( 3837): Wait PC Thread 1=false 2=true
>07-30 11:06:28.107 I/Zygote  ( 3837): Wait PC Thread 1=false 2=true

And

>07-30 11:06:28.117 I/DEBUG   (  303): pid: 3837, tid: 4147, name: Thread-11  >>> zygote <<<
>07-30 11:06:28.117 I/DEBUG   (  303): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3c
>07-30 11:06:28.157 I/DEBUG   (  303): Abort message: 'art/runtime/jni_internal.cc:771] JNI **FatalError** called: RegisterNatives failed for 'android/media/MediaRecorder'; aborting...'
>07-30 11:06:28.157 I/DEBUG   (  303):     r0 131aa380  r1 00000000  r2 00000000  r3 00000000
>07-30 11:06:28.157 I/DEBUG   (  303):     r4 131aa380  r5 b6f2fe04  r6 a96fe4f8  r7 b4d13381
>07-30 11:06:28.157 I/DEBUG   (  303):     r8 a941a0c0  r9 00000000  sl a941a0c0  fp 131aa3b8
>07-30 11:06:28.157 I/DEBUG   (  303):     ip a941a0c4  sp a96fe390  lr b4cd12e5  pc b4cbbb56  cpsr 400e0030


There are some more, I think all similar. Does this seems like a possible cause? Do I continue looking? And is it just FATAL or also FatalError like I put up here? Thanks!

**Comment by M66B** [comment]
The ART runtime is crashing, so this is most likely caused by a buggy Xposed version and therefore not an XPrivacy problem.
