### ISSUE TITLE
Fail to install Xposed Framework 5.1.1

### ISSUE THREAD

**Issue by pquerner** [M66B/XPrivacy#2244]
I am running Cyanogemmod 12.1 (20150727-nightly-sirius) on my Sony Xperia Z2 mobile phone and I am unable to install the Xposed Framework as it says:

```
Xposed is not (yet) compatible with Android SDK version 22 or your processor architecture (armeabi-v7a).

CANNOT LINK EXECUTABLE DEPENDECIES: library "libdvm.so" not found.
```

What shall I do?

**Comment by M66B** [comment]
Xposed for Android 5.x needs to be installed in another way. See the Xposed XDA forum threads for details.

**Comment by pquerner** [comment]
Then the documentation is wrong. It says just to install the Xposed framework in the install instructions. (And its testet up to 5.1.1)
Nothing about "if you're on 5.x do this and that".

But thanks, I'll try to find that thread.
