### ISSUE TITLE
No sound in voice call

### ISSUE THREAD

**Issue by ankytt** [M66B/XPrivacy#2248]
Hi, I am using XPrivacy in lollipop 5.1.1 in Moto G XT1068. As soon as i enable XPrivacy, i can't hear voice in phone calls or front speaker stops working. Is this a bug?

**Comment by M66B** [comment]
I don't think this is caused by a bug, but is caused by a restriction.
Please read this:
https://github.com/M66B/XPrivacy#support

**Comment by ankytt** [comment]
Hi @M66B,

What could be possible issue? I am restricting only one app right now.

**Comment by M66B** [comment]
Maybe this FAQ can help:
https://github.com/M66B/XPrivacy#FAQ63
