### ISSUE TITLE
XPrivacy crashed on app updates

### ISSUE THREAD

**Issue by Findus23** [M66B/XPrivacy#2250]
Most of the time, when I update an app, a message pops up, saying that XPrivacy has crashed. 

A short Logcat after updating OpenKeychain from F-Droid: https://gist.github.com/Findus23/03799aeedade8a748eb7 (if I cut away something important [the full logcat](https://gist.github.com/Findus23/236e4ff86d0a2db74830))

I have no idea about java, but I think the error has something to do with this line:
```
W/XPrivacy( 8563): android.app.RemoteServiceException: Bad notification posted from package biz.bokhorst.xprivacy: Couldn't create icon: StatusBarIcon(pkg=biz.bokhorst.xprivacyuser=0 id=0x7f02004b level=0 visible=true num=0 ) uid=10099
```

Unfortunately I can't reproduce the error. It mostly happens when I update an app for the first time after a reboot.
If it is possible, I will add a second logcat with XPrivacy debug logging enabled.

UPDATE: That's odd! The error was happening quite frequently for some time, but now, when I want to make a logcat I can't reproduce it anymore.

**Comment by M66B** [comment]
This problem has been reported before and is most likely caused by a bug in you ROM.
XPrivacy creates notification through the Android APIs in a standard way, so there is little that can be done to workaround this problem.

**Comment by Findus23** [comment]
Okay, thanks at that quick response. I am using CM12.1 nightly, so I believe the bug will be fixed soon. 

Lukas
