### ISSUE TITLE
XPrivacy deletes ExchangeActiveSync Account

### ISSUE THREAD

**Issue by john256** [M66B/XPrivacy#2253]
I've been using XPrivacy for a few years, but this issue is new, possibly triggered to an update to the latest version.

I found that my calendar has stopped showing any entries, and then I noticed that the Exchange account has disappeared. Eventually, I managed to track the problem down do XPrivacy.

With XPrivacy disabled/removed, I am able to create an Exchange account and use it normally.
From there, after installing/enabling XPrivacy and rebooting, the Exchange account has disappeared (and doesn't come back after removing/disabling XPrivcay).
Trying to set up the Exchange account with XPrivacy enabled, there's a message that Exchange services have stopped before setup is complete.

I'm not sure there are any settings I could change because the software only shows restrictions for user apps, not system apps.

Android version 4.3 (latest available for device)
Device Sony Xperia SP (C5303)
XPosed Framework app_process 58/XposedBridge.jar 54
XPrivacy 3.6.19

Thanks.

**Comment by M66B** [comment]
I am quite sure this is not caused by a bug but by a restriction.
I don't know which one, however.
Your best bet is to ask for help in the XDA XPrivacy forum.

Please read this too:
https://github.com/M66B/XPrivacy#support
