### ISSUE TITLE
Facebook permissions?

### ISSUE THREAD

**Issue by xperiauser** [M66B/XPrivacy#2260]
First off, Thank you for creating an app to do this sorta stuff. I don't see facebook under apps to set permissions, only the messenger. Any idea why it wouldn't be showing up? I have an xperia z 4.3.

**Comment by M66B** [comment]
See this FAQ:
https://github.com/M66B/XPrivacy#FAQ74

Please read also this:
https://github.com/M66B/XPrivacy#support
