### ISSUE TITLE
Use Xprivacy to fix the vexatious "outgoing call marked as unknown" issue 

### ISSUE THREAD

**Issue by DamienGrand** [M66B/XPrivacy#2263]
Long story short, this is probably a question than an issue.

There is a nasty bug on Lollipop that makes an OUTGOING call marked as "unknown" because misconfigured carrier systems send a "request to hide the number"

https://forums.motorola.com/posts/5765f24ce4

Since Dialer in Lolipop is more or less vanilla app that is doing more or less vanilla-app things, maybe it should be possible to detect when this particular exchange happens and use Xprivacy to prevent the buggy request from ever reaching Dialer?

I have several numbers in my contacts that exhibit this behavior and XPrivacy working.

What steps should I take to narrow it down to specific permission block and/or help implement necessary features ?

**Comment by M66B** [comment]
Sorry, but XPrivacy is not meant to fix bugs in other applications and/or system components.
