### ISSUE TITLE
Post #1 on XDA requires minor update

### ISSUE THREAD

**Issue by Gitoffthelawn** [M66B/XPrivacy#2265]
When we updated README.md, the anchor for the FAQ changed (I added "FAQ" to the text to improve search accessibility).

So, in post number 1 in the XDA thread, the anchor to the FAQ needs to be updated as well. Furthermore, there is now an HTML anchor available for the screenshot section, so that can be added to XDA post number 1.

**Comment by M66B** [comment]
I missed this. Could you please make a pull request to add the old anchor as well. Post #1 is not the only thing pointing to the GitHub documentation ...

Gitoffthelawn <notifications@github.com> schreef op 25 september 2015 23:05:23 CEST:

**Comment by Gitoffthelawn** [comment]
Yes. I'll get on it right away.

**Comment by Gitoffthelawn** [comment]
OK... ready to merge.  I will be able to test it once merged.

You can add the screenshots anchor to XDEA post 1 if you like.

**Comment by Gitoffthelawn** [comment]
Provided a refinement that is ready to merge.

**Comment by Gitoffthelawn** [comment]
All good now.
