### ISSUE TITLE
Request : initial permissions

### ISSUE THREAD

**Issue by TheDarkEyed** [M66B/XPrivacy#2276]
Sometimes it's quite boring to keep allowing/denying simultaneously. 😜 It would be great if you could implement a feature where user finds all the permissions and select which ones to allow/deny for an app while launching it for the first time. ☺ 
Thanks for this great app! 👍

**Comment by M66B** [comment]
This is what the crowd sourced restrictions are for:
http://crowd.xprivacy.eu/
