### ISSUE TITLE
Restrictions not working in 3.6.19 for some apps

### ISSUE THREAD

**Issue by kataki** [M66B/XPrivacy#2277]
Hi
when restricting some settings like
Device ID, IMEI for some apps its still showing the real one (one of the apps is samsung phone info+)
i tested another apps like elixir2 and network info II and they show the fake info 
i am applying same permission to the samsung phone info+ and other apps (and i didn't allow su access) and still its showing the real info
is there anything i am missing or doing wrong?
i am using xprivacy 3.6.19 (481) pro version
running in compatibility mode on samsung s5 duos sm-g900fd android 4.4.2 (19)
thanks in advance

**Comment by M66B** [comment]
If a restriction works for one application, it works for all applications, so there is no bug. The application might be caching the value or even have stored it. Ask on the XDA XPrivacy forum if somebody knows more.
