### ISSUE TITLE
XPrivacy reports that every app has certain media permissions

### ISSUE THREAD

**Issue by Gitoffthelawn** [M66B/XPrivacy#2292]
I was performing some testing, and I had Filter set to *Filter on permissions*.  By doing this, I noticed that XPrivacy thinks **every** app has permissions for these items in the *Media* category:

* android.media.action.IMAGE_CAPTURE
* android.media.action.IMAGE_CAPTURE_SECURE
* android.media.action.VIDEO_CAPTURE

Is this a bug or by design?

Test version: XPrivacy Pro v3.6.19 (481) running in compatibility mode

**Comment by M66B** [comment]
Every application has these permissions (actually there is no Android permissions at all for this).

I would be grateful if you looked through the texts here:

**Comment by M66B** [comment]
I would be grateful if you looked through the texts here:
https://github.com/M66B/NetGuard

**Comment by M66B** [comment]
The Android permissions for all restrictions are defined here:
https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/Meta.java

**Comment by Gitoffthelawn** [comment]
*I would be grateful if you looked through the texts here:
https://github.com/M66B/NetGuard*

You got it.  Looking at them now.  Do you want help with them, if needed?

**Comment by M66B** [comment]
Yes, please and testing NetGuard would be welcome as well.

**Comment by Gitoffthelawn** [comment]
Editing now...

**Comment by Gitoffthelawn** [comment]
Editing finished.  Pull requests initiated.

Unfortunately, I won't be able to test the NetGuard APK at this time, as I am not working with any Lollipop or Marshmallow devices.

Looks great.

**Comment by Gitoffthelawn** [comment]
*Every application has these permissions (actually there is no Android permissions at all for this).*

In regards to this issue, I'm thinking about what is best, and am interested in your thoughts as well.

On one hand, since no permission is required to access that functionality (which is an atrocious decision by Google), it is good that XPrivacy indicates that every app has that permission.

On the other hand, by indicating that apps have this permission, it looks like apps are intentionally trying to have permission to use the camera, even though they are not.  This effect gets magnified when you use XPrivacy filters or searches, which causes only certain apps to be displayed.  This has fooled me, resulting in spending time going through source code line-by-line to see why an app is using the camera... only to discover that it is not.

What are your thoughts?

**Comment by M66B** [comment]
I like to keep the UI as consistent as possible, so I don't like to have a special indication for this.
The application has in fact access is what matters.

**Comment by Gitoffthelawn** [comment]
Yes, this is a tricky case.  Would you like me to add an item to the FAQ regarding this idiosyncrasy?

**Comment by M66B** [comment]
Yes, please

**Comment by Gitoffthelawn** [comment]
Will do.  Busy now, but on my near-term list to complete that task.

I also noticed that XPrivacy indicates every app has permissions for at least one other item (IPC Binder).  I'll include that in the FAQ as well.
