### ISSUE TITLE
Ominious behaviour of QueryIntentActivities and Srv_QueryIntentActivities blocking in 3.6

### ISSUE THREAD

**Issue by DreamFlasher** [M66B/XPrivacy#2299]
SUMMARY/GOAL:
dkbpushtan performs a root check on startup and denies usage if root is detected. That's why a lot of people want to use XPrivacy for root cloaking of this app. 

REPRO STEPS: 
1) Install https://play.google.com/store/apps/details?id=com.starfinanz.mobile.android.dkbpushtan
2) Use XPrivacy 3.6 (and higher)
3) Disable access to QueryIntentActivities and Srv_QueryIntentActivities to dkbpushtan
4) Start dkbpushtan

RESULT:
dkbpushtan crashes

EXPECTED:
dkbpushtan does not crash (this is the behaviour of Xprivacy 3.5)

Which changes to QueryIntentActivities and Srv_QueryIntentActivities did you make between 3.5 and 3.6?

**Comment by M66B** [comment]
Root cloaking is not supported, sorry.

**Comment by DreamFlasher** [comment]
But why does it work in 3.5 and not in 3.6?

**Comment by M66B** [comment]
Also, these functions are marked as dangerous for a reason, so crashes can occur.

**Comment by M66B** [comment]
I don't know.

**Comment by M66B** [comment]
I don't know.

**Comment by DreamFlasher** [comment]
Super Antwort. Wisse mer net, is uns auch sch egal.

**Comment by M66B** [comment]
XPrivacy is open source, so you can easily check yourself. GitHub has even a compare view. The point is your use case is not supported, XPrivacy is meant to protect your privacy, not to hide root.

**Comment by cYbercOsmOnauT** [comment]
But hiding that I rooted my phone is also a part of protecting my privacy. I want to be able to set who is able to know this and who not.

**Comment by M66B** [comment]
XPrivacy is a free and open source project, so you are free to contribute this feature if you like.

**Comment by cYbercOsmOnauT** [comment]
If I would be able to do so I would have done it already. I am a coder since decades but not for Java. So what other possibility besides writing here do I have? Learning Java? :grin: Or maybe send you another donation? :wink:

**Comment by M66B** [comment]
Donations are completely voluntary, like my work for this project.

**Comment by cYbercOsmOnauT** [comment]
I know... but that is one of the only options I have :wink:
