### ISSUE TITLE
Randomizing of some id's

### ISSUE THREAD

**Issue by mtraf** [M66B/XPrivacy#2303]
Hi! 
I need the privacy in one apk. This apk parse some id's and understand - are you real or fake. They

**Comment by mtraf** [comment]
If I have specified the local task and only I need it can you make these changes for me for money? If yes, how can we communicate and decide the price of this task?

**Comment by M66B** [comment]
You can reach me at marcel(plus)xprivacy(at)faircode(dot)eu
