### ISSUE TITLE
Hook.isAvailable has bug

### ISSUE THREAD

**Issue by zhangqing123** [M66B/XPrivacy#2304]
if (mObsolete)
			return false;
if (Build.VERSION.SDK_INT < mSdkFrom)
			return false;
if (Build.VERSION.SDK_INT > mSdkTo)
			return false;
if (mAOSPSdk > 0 && !isAOSP(mAOSPSdk))
			return false;
if (mNotAOSPSdk > 0 && isAOSP(mNotAOSPSdk))
			return false;
		return true;
!isAOSP and isAOSP return false

**Comment by M66B** [comment]
I don't see a bug.

**Comment by zhangqing123** [comment]
i use in nexus 6 sdk 22.
i hope set new IMEI. XTelephonyManager.getDeviceid.
 but when call hook , isAvailable return false, the Method not hook

mAOSPSdk  = 0
in if (mAOSPSdk > 0 && !isAOSP(mAOSPSdk))  isAOSP return true
but  if (mNotAOSPSdk > 0 && isAOSP(mNotAOSPSdk))
mNotAOSPSdk  = 19 isAOSP return true
so isAvailable return false .

**Comment by M66B** [comment]
This is not a bug, because AOSP mode has not been tested with SDK 22

**Comment by zhangqing123** [comment]
Thank you for your prompt reply.And  I want to know what the function of AOSP

**Comment by M66B** [comment]
There is a FAQ about this and it has been discussed many, many times on XDA.

**Comment by zhangqing123** [comment]
Thank you
