### ISSUE TITLE
Xprivacy not catching license

### ISSUE THREAD

**Issue by SOLiNARY** [M66B/XPrivacy#2313]
Ive got rooted Xperia Z. Got license by donating, put license in root sd card, restarted phone, app still redirects me to buy mr license when i want to import restrictions.

**Comment by M66B** [comment]
There is a FAQ about license problems, did you check the suggestions already?


Ramin Quluzade <notifications@github.com> schreef op 24 december 2015 13:33:04 CET:

**Comment by SOLiNARY** [comment]
Yeah, I placed it in 4 places root folders and Download folders of both SDCARD & INT storage.
Now it is licensed though it didn't remove this file from any of these folders so I dont know which is exactly correct.
I think this FAQ (or link to it) needs to be added to email sent after purchasing.

Thanks.
