### ISSUE TITLE
Function being restricted even though not restricted

### ISSUE THREAD

**Issue by Gitoffthelawn** [M66B/XPrivacy#2314]
I ran across an issue that could be a bug... or not.  Before I spend half an hour composing a detailed bug report (time I don't have at the moment), let me first present an overview to see if it's worthwhile.

A non-detailed overview of the issue:
1. Created a template that restricts some internet functions with on-demand queries (double checkboxes) and allows other internet functions with on-demand queries (right checkbox only).
2. Applied template to a specific app.
3. Ran the app.
4. Several on-demand windows open up, one at a time.  Answer yes to each one, whitelisting as I go along.

Actual Result: XPrivacy log shows one of the functions was restricted for an item that was explicitly whitelisted via an on-demand window.  This function is one that was "on-demand default allowed".

Expected Result: No internet functions restricted by XPrivacy.

**Comment by M66B** [comment]
With a million users it is quite unlikely that there is a bug in the on demand restricting.

I miss details and a logcat, so there is nothing Uy can look into.

Did you allow a function with specific parameters?
Did you take into account the caching time?

**Comment by Gitoffthelawn** [comment]
It's certainly the first time I've noticed anything unusual like this with XPrivacy.

I tested it a half-dozen times, and it had the same issue each time.  But I was pressed for time, and I don't think I allowed a full 15 seconds for caching.  That could well be the issue.

BTW, what do you mean by "Did you allow a function with specific paramters?"  Do you mean functions like `proc`?  If so, yes,  Why does it matter?

**Comment by M66B** [comment]
Whitelisted parameters are exceptions to normal restrictions.

**Comment by Gitoffthelawn** [comment]
Right. Except this item was whitelisted, but still restricted.  In hundreds of apps that I've closely analyzed and monitored with the XPrivacy Usage Data logs, I've never seen this happen before.  That's why I kept repeating the test, and it kept doing it again and again.

Now that I think of it, I don't think the caching requirement is the issue.  If a URL is whitelisted for a function, and the app calls it again right after it is whitelisted, it should still be unrestricted, right?

**Comment by Gitoffthelawn** [comment]
BTW, here is the app: https://play.google.com/store/apps/details?id=mkisly.corners.mini

Although it's an enjoyable and well-written little game, it's not an essential app (I already deleted it).

But I mention it if it can be used to demonstrate an issue with XPrivacy.

I may not have time to post here for a number of days, so I thought it best to add this info.
