### ISSUE TITLE
Feature request: status icon

### ISSUE THREAD

**Issue by burner1024** [M66B/XPrivacy#2316]
So I've set up Xprivacy some time ago, and was using it happily. Until today, when I opened Xprivacy and discovered that it's not enabled. Missing some modules from Xposed, or something like that. I re-installed it and it started working again. But what's done is done, all my data is no longer private. (And all efforts in Xprivacy configuration went to waste).

I didn't disable it on purpose, that's for sure. Must've been some Android update or such. The point is, without a visible indicator (and preferably, an internet killswitch), it's just not reliable.

I would suggest to add a permanent status icon (like Adblock, or some antivirus software do).

**Comment by M66B** [comment]
Unless you suppress notifications, for example using an Xposed module, XPrivacy will notify you when it is disabled.

**Comment by burner1024** [comment]
I've no idea how to do that, but definitely wasn't showing anything.
