### ISSUE TITLE
Not working with uber, taxi for sure and ola app

### ISSUE THREAD

**Issue by Chandankrk** [M66B/XPrivacy#2318]
Those app detected genuine details 
I am changed everything and check with device id by evozi every permission like android id, device id, gsf id, mac address, bluetooth address, sim subscriber id, sim serial no. (Changed in donkey guard) hardware serial no., local ip address hiden

But uber by pass location, internet access and show actual loaction.

Change phone model no. brand name and manufactured name by es file explore (device/system/build.prop)

But company detect my phone, and blacklisted my phone every time

Pls install uber, taxi for sure and ola app and check how spoofing all permission 

My email address is chandankr.2005@gmail.com

Cell no. 9891754050

Sorry i dont know good English 

Thanks

Chandan

**Comment by M66B** [comment]
There has recently been questions answered about restriction locations to an application in the XDA XPrivacy, please read these answers.

Internet access can be restriction by the (dangerous) function restriction inet in the internet category. Note that this restriction requires a full application restart to be applied.

XPrivacy is not there to prevent detection of your phone, but to protect your privacy. See also the red texts in the opening post on XDA.
