### ISSUE TITLE
Xprivacy is not installed,  enable in xposed,  Device restartbis required,  this always shows when ever i try to use xprivacy 

### ISSUE THREAD

**Issue by NightMaze** [M66B/XPrivacy#2320]

**Comment by M66B** [comment]
There is a FAQ about this with suggestions.
If this doesn't help I need a logcat.

**Comment by NightMaze** [comment]
cqn u please give me the link about the post resolving this issue,  thank you

**Comment by M66B** [comment]
https://github.com/M66B/XPrivacy#frequently-asked-questions-faq

**Comment by NightMaze** [comment]
i cant use this app i did complete xprivacy installer procedure,  but when i open xprivacy it says Device Resort Required.....  
i already seen in FAQ there is not any post resolving this, :( 
thanks you

**Comment by M66B** [comment]
Then I need a logcat captured from your PC, starting before turning on your device.
There is a FAQ about capturing logcats.
