### ISSUE TITLE
Where exactly is XposedBridgeApi-20150213.jar from?

### ISSUE THREAD

**Issue by msdos** [M66B/XPrivacy#2321]
For some background (and motivation), read this post in [Xposed itself](https://github.com/rovo89/XposedTools/issues/6).

Thanks in advance for this big application you have done to the android community.

**Comment by M66B** [comment]
It was made available by the Xposed developer.

**Comment by msdos** [comment]
Thanks for answering. Indeed, this info is from XposedBridge documentation itself in https://github.com/rovo89/XposedBridge/wiki/Development-tutorial

Did you compile it yourself or downloaded from http://forum.xda-developers.com/xposed/xposed-api-changelog-developer-news-t2714067?

**Comment by M66B** [comment]
I trust the Xposed developer, so it was downloaded.

**Comment by rovo89** [comment]
Note that it doesn't really matter where the file is coming from as it isn't included in the final APK. It's just referenced, i.e. made available in the CLASSPATH of the compiler to compile the module's classes against.
