### ISSUE TITLE
Whitelists are not exported/imported

### ISSUE THREAD

**Issue by HyperCriSiS** [M66B/XPrivacy#2322]
Hi,

Actually I only use account whitelisting.
When I export the settings I apply not filter.
Before the import I assure that all accounts are available.
After the import the apps don't have the whitelisted accounts configured.

Is there still anything that I could have done wrong?

Thanks in advance.
Hyper

P.S.: Did you gave up development on xprivacy?

**Comment by M66B** [comment]
Accounts are exported and can be imported, but only onto the same device.

I still support XPrivacy and I will fix critical bugs. I have written on this on XDA.

**Comment by HyperCriSiS** [comment]
Hi,

it is always the same device and even the same ROM.
Just updated ROM version.
What could be the cause?

Regards,
Hyper

**Comment by M66B** [comment]
Updating your ROM version is probably the cause, since it might the device ID to change.

**Comment by HyperCriSiS** [comment]
I think you pointed me to the issue. Thanks!!
Just searched for your comment concerning development status, but I could not find it anywhere...
