### ISSUE TITLE
xprivacy not active with new applications

### ISSUE THREAD

**Issue by bernalaurelio** [M66B/XPrivacy#2323]
Hello

I installed the stable version xprivacy and I realized that if I install a new application on my phone does not alert me xprivacy permits this teniedo the newly installed app.

To receive alerts of new application I have to enter and search xprivacy the newly installed application and then check the options to prompt me for each permit that requires the application.

Is there any way to monitor all xprivacy mitelefono applications imcuidas the newly installed?

Thank you for your help

Aurelio Bernal

**Comment by M66B** [comment]
You'll need to define a template to be applied to new applications. For follow up questions, please use the XDA XPrivacy forum.

**Comment by bernalaurelio** [comment]
Hello

And I found the error.
greenify I have installed on my phone and the application of xprivacy was being hibernated therefore not activated.

Thank you
