### ISSUE TITLE
Building from source code should be described in README.md or BUILDING.md

### ISSUE THREAD

**Issue by vi** [M66B/XPrivacy#2324]
Usual `android project update`, `ant debug` seems to fail (`/opt/androidsdk/tools/ant/build.xml:573: ../../sdk/extras/android/support/v7/appcompat resolve to a path with no project.properties file for project /mnt/src/git/XPrivacy`).

After adjusting paths to appcompat and cardview it produces this:

     ...
     [aapt] Generating resource IDs...
     [aapt] /mnt/store2/opt/adt-bundle-linux-x86-20130219/sdk/extras/android/support/v7/appcompat/res/values-v21/styles_base.xml:75: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton'.
     ...
    
There should be proper instructions how to build XPrivacy from source code, preferrably using command line on Linux computer with only Android SDK being set up.

Maybe with Gradle-based build system it would be easier?

**Comment by M66B** [comment]
If you are trying to build yourself, it is assumed you know how to and you are able to solve any build problems. Else you should use the published builds.

**Comment by vi** [comment]
After a bit of hacking built XPrivacy v3.6.19 using modified supplied gradle file `tools/build.gradle`:

```
buildscript {
	repositories {
		mavenCentral()
	}

	dependencies {
		// classpath 'com.android.tools.build:gradle:0.12+'
        classpath 'com.android.tools.build:gradle:1.3.0'
	}
}

apply plugin: 'com.android.application'

dependencies {
	compile files('libs/android-support-v13.jar')
	compile files('substrate-api.jar')
	provided files('XposedBridgeApi-20150213.jar')
	compile 'com.android.support:appcompat-v7:23.0.0';
	compile 'com.android.support:cardview-v7:23.0.0';
}

android {
	compileSdkVersion 23
	buildToolsVersion "23.0.2"
	
    useLibrary  'org.apache.http.legacy'

	sourceSets {
		main {
			manifest.srcFile 'AndroidManifest.xml'
			java.srcDirs = ['src']
			resources.srcDirs = ['src']
			aidl.srcDirs = ['src']
			renderscript.srcDirs = ['src']
			res.srcDirs = ['res']
			assets.srcDirs = ['assets']
		}
	}
}
```
