### ISSUE TITLE
entries in contact whitelist seem to duplicate themselves

### ISSUE THREAD

**Issue by kaergel** [M66B/XPrivacy#2326]
I restricted access to my contact list for specific apps. Since then Xprivacys whitelist seem to have double entries for some contacts. This issue seems to get worse over time. Last time i checked some contacts had ~20 entries.

Restricted apps are threema, telegram and whatsapp. Rom is CM12.1 unofficial (Modpunk) on a Samsung G850F. I also noticed this behaviour on Samsungs Kitkat Stockrom  and a Samsung t325n tablet with CM12.1 before.

I exported the restrictions and analyzed  them. There are no double entries in the exported xmls.
![screenshot_2016-02-17-10-35-33](https://cloud.githubusercontent.com/assets/6215543/13105625/68becc54-d564-11e5-9db7-786d194f7e97.png)

**Comment by M66B** [comment]
This is a cause of restricting contacts. Some applications add the contacts again from their external server. This cannot be fixed 

"Thomas Kärgel" <notifications@github.com> schreef op 17 februari 2016 10:53:21 CET:

**Comment by kaergel** [comment]
ok, i understand. So i went ahead and restricted whatsapps access to it's own account on my android device 8)... strange enough but whatsapp seems to run fine without access to it own account. Next time it will fail creating double entries ;). Then i used my contact manager, viewed only my whatsapp contacts and deleted all double entries. So far so good. At this point I hoped Xprivacy will also reread my contacts and the double entries would be gone, but nope. Restarting the Xprivacy doesn't help, device reboot doen't help. What do i have to do to trigger the rebuild of the whitelist? Thx in advance

**Comment by M66B** [comment]
The contacts shown in XPrivacy are coming from Android. XPrivacy does not store contact info, only restrictions.
