### ISSUE TITLE
Restricting Internet do not block Internet access

### ISSUE THREAD

**Issue by cy18** [M66B/XPrivacy#2327]
I'm using Android 6.0

I restricted the Internet and Network permission of an APP, but it can still access to the Internet. It seems  restricting the Internet do not restrict most of the functions under Internet category, because these function are red and "dangerous to be restricted".  I tried checking all the functions under Internet category and the Internet access is blocked. 

I don't  think it's a good idea to check these functions one by one for all the apps that I want to block Internet access.

**Comment by M66B** [comment]
This has been discussed several times on XDA.

**Comment by cy18** [comment]
Any links? I tried searching but found nothing.
