### ISSUE TITLE
Xprivacy vs. Uber

### ISSUE THREAD

**Issue by MichaelVarch** [M66B/XPrivacy#2330]
Xprivacy doesn't seems to work with the Uber App. Uber blacklisted (still don't know why) my phone (Nexus 5), I don't have the $ to buy a new phone, and frankly I don't want to, so I am trying to make the Uber App believe that my blacklisted Nexus 5 is another device using Xprivacy's Fake Data settings, but it doesn't work, and when I say that it doesn't work, I mean that it doesn't work at all.

Using Xprivacy 3.6.19, Android 4.4, Xposed 2.7

What I've noticed: blocking permissions work, it definitely does, but feeding the app with fake data doesn't.

I tried a lot of Uber.apk thinking maybe the old versions weren't sophisticated as the new ones, but no luck. I even tried with Lollipop and Marshmallow, still no luck.

I checked every boxes possible (that won't make the app crash) using expert mode, but somehow Uber still knows.

I've been trying for a week now, I tried every settings possible, I'm about the give up, you're my last hope.

I'll PayPal you $100 if you can help me. Thanks mate.

**Comment by M66B** [comment]
Faking another device is not supported
