### ISSUE TITLE
WiFi and Bluetooth issues

### ISSUE THREAD

**Issue by jakenl** [M66B/XPrivacy#2332]
I have issues on a very not repetitive base that I can't enable WiFi and/or Bluetooth. I team a logcat and came across a bunch of roots errors. One of them was: 
02-29 22:06:21.531 E/BluetoothA2dpSink(757): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)

Searching for this message online, gave me a Google result that made a connection with xPrivacy.
Can I help by sending that logcat file?

**Comment by M66B** [comment]
I don't think this is caused by a bug in XPrivacy.

**Comment by M66B** [comment]
It might be caused by a restrictions and maybe someone in the XDA XPrivacy forum knows more.
