### ISSUE TITLE
Need to require permission on SDK23

### ISSUE THREAD

**Issue by jipzingking** [M66B/XPrivacy#2335]
Please update SDK version to 23 since Samsung 6.0 will not assign any user-defined permission to package by default such as biz.bokhorst.xprivacy.MANAGE_XPRIVACY result that XPrivacy app will run as usual without any notification but no restriction will work at all.

**Comment by jipzingking** [comment]
However, user could toggle that permission in Settings, so remind user to open it could be a temp solution.

**Comment by M66B** [comment]
This permission is not needed to run XPrivacy

**Comment by jipzingking** [comment]
I just misunderstood how it work and feel sorry about it.
