### ISSUE TITLE
Function "Clear" in the Fetch community filters dialog is unclear

### ISSUE THREAD

**Issue by drws** [M66B/XPrivacy#2340]
Function "Clear" in the Fetch community filters dialog is enabled by default, loosely worded (Clear WHAT) and undocumented in help/FAQ...

**Comment by M66B** [comment]
This check box means clear existing restrictions before applying fetched restrictions.

**Comment by drws** [comment]
Ok, but was this explanation also added to the documentation before the bug was closed?

**Comment by M66B** [comment]
XPrivacy is an open source community project, so you could contribute this to the project.

**Comment by drws** [comment]
XPrivacy Pro with community rules referenced in this issue also is a payable app. Definitely not the cheapest I might add. Informative documentation is expected at this point and don't get me even started on the whole community rules implementation. A measily template is everything that the software is capable of automatically applying upon the installation of the app - where is the auto community rule download? Auto community rules update? Block app execution if community rule is not found?

**Comment by Gitoffthelawn** [comment]
@drws Have you updated the FAQ with the information that was provided to you?

**Comment by M66B** [comment]
`XPrivacy Pro with community rules referenced in this issue also is a payable app. Definitely not the cheapest I might add. Informative documentation is expected at this point and don't get me even started on the whole community rules implementation. A measily template is everything that the software is capable of automatically applying upon the installation of the app - where is the auto community rule download? Auto community rules update? Block app execution if community rule is not found?`

Everybody wanting to get the pro features visits [this page](https://www.xprivacy.eu/), where you can see that contributing to the project is completely voluntarily. I think it is fair that "voluntary" applies to myself as well. I am paying for the [crowd sourced restrictions](https://crowd.xprivacy.eu/) servers and have contributed more than 2500 hours to the XPrivacy project. What did you contribute?
