### ISSUE TITLE
The "Search" button is not work

### ISSUE THREAD

**Issue by lzxil00** [M66B/XPrivacy#2345]
Hello!
I install the Xposed Framework and Xprivacy successfully and I run it, but  when I choose "Settings", want to fake the data, I find the "SEARCH" button is not work, it's unable to press(button is gray) , and I could not change or edit the text "Christmas Island". 
Of course other functions are working including "RANDOMIZE NOW". I really want to use that feature, it could let me set my location in where I want, not randomly. T_T

Driver: Mi4-LET-CT 
Android version:6.0.1

Thanks.

**Comment by M66B** [comment]
See the FAQ about this.
While you are there, please read the support section as well.

**Comment by lzxil00** [comment]
@M66B 
I'm so sorry about that, so I find it in FAQ, and.....

"(20) Why is the Settings > Fake data > Search button disabled?
Because some Google components are not installed."

I use open gapps and install the nano Variant,
but it still not work, could u tell me which Google components I need to install?
Thanks again.

**Comment by lzxil00** [comment]
I even try the Stock variant Aapps, it seems use AOSP to replace installed apps or components, but sitill not work. T_T....

**Comment by M66B** [comment]
What is needed is the Geocoder, but I don't know which Google component offers this service.

**Comment by lzxil00** [comment]
Ok, it seems Google Maps has it, I'll try it again, Thank u very much.
