### ISSUE TITLE
Cyanogen OS (Cyngn) 13 detected as compatibility mode

### ISSUE THREAD

**Issue by Jamesits** [M66B/XPrivacy#2350]
Cyanogen OS is CyanogenMod's official commercial fork, which should be fine for XPrivacy running in AOSP mode. However it's detected as compatibility mode. 

Tried to force enable AOSP mode and it worked well. 

![image](https://cloud.githubusercontent.com/assets/1297257/15169923/44fb5da4-1773-11e6-8193-3c86ce868f94.png)

FYI: [Cyanogen OS Homepage](https://cyngn.com/)

**Comment by M66B** [comment]
Cyanogen OS has too many changes from AOSP to have XPrivacy running in AOSP mode.
