### ISSUE TITLE
Xposed not compatible with Marshmallow, use Xprivacy for testing purposes

### ISSUE THREAD

**Issue by cousinjo** [M66B/XPrivacy#2351]
I have been using Xprivacy for a long time and never had any issues until now.
Recently I got a new phone running Marshmallow and unfortunately Xposed doesn't work on it, so I can't use Xprivacy.
Still, I'd like to use it for testing. I mean, I know it can't restrict anything since Xposed isn't active but I'd like to use iit to see what data apps ask for.
The problem is that when I install Xprivacy it brings me to the Xposed not enabled screen, which is normal behaviour.
I have downloaded Xprivacy's source, I removed the Xposed jar and all the Xposed references in the code and successfully built the app but without any success, the Xposed not enabled screen keeps on popping out when I install the modified Xprivacy.
I have 3 questions.
First, is it possible at all to have Xprivacy to open normally without Xposed installed?
Second, if Xprivacy can somewhow open without Xposed, could Xprivacy show me the data apps request even if Xposed isn't installed?
Third, if both above conditions are met, how can I disable the Xposed check?
Thanks to all for any answer.

**Comment by M66B** [comment]
XPrivacy needs Xposed to work, also to see what is being accessed.

cousinjo <notifications@github.com> schreef op 16 mei 2016 12:33:05 CEST:

**Comment by cousinjo** [comment]
Ok, thanks for the quick reply (OMG, that was really quick:-)), now I know...
