### ISSUE TITLE
New Feature Requested

### ISSUE THREAD

**Issue by stud007** [M66B/XPrivacy#2354]
Xprivacy doesn't allow to select which running app proceess we can give to any app which having acess to running app proceess,  As u have option to select install package to read by app that is gud but beacuse of running app proceess permission your app can't control fully any app
So i need feature of blacklist some running app proceess to read by xyz app

**Comment by M66B** [comment]
This is already possible.
If you don't know how, ask in the XDA XPrivacy forum how to.
Please read the section on support too.

**Comment by M66B** [comment]
Note that this feature is a pro feature.
http://www.xprivacy.eu

**Comment by stud007** [comment]
Sir i already have pro app but don't know how to do this can u please give
me any link to that post will be helpful to me

**Comment by Cerberus-tm** [comment]
@stud007 In Xprivacy, click on an app so that you see the app's permissions. Then click on the menu button (three dots in the upper-right corner). Pick "select applications to allow". This only works if you have access to running/instaled applications restricted for that app.

**Comment by stud007** [comment]
Thanks for your information Sir, but i already tested this and it is
limited to only install package/application and working fine.
But my main concern is to filter same list of application in running stage
means list from command get.running.services or from list of
activty.manager i think it is going empty to the current app for which this
option has been restricted and because of empty list that app is not
working as it should be.
