### ISSUE TITLE
Numerous Problems on XPrivacy

### ISSUE THREAD

**Issue by me102** [M66B/XPrivacy#2356]
Dear Marcel,

I'm using XPrivacy Pro 3.6.19 on Samsung Galaxy S7 (SM-930FD).
OS: Android 6.0.1
Xposed Framework: v85.1 - custom build by "wanam"

My original intention was to elaborate the numerous problems I've been dealing with since I started using XPrivacy on the aforementioned device, but first I'd like to ask about something important that I wasn't able to get an answer to: **is it true that the latest XPrivacy version available was released almost a year ago?**
I remember that you used to release new versions very frequently in the past, so I find it very strange that no one has raised this question until now, and that the official XPrivacy page does not refer to this issue.

**Am I missing something?...**

I appreciate your help!
Also, I apologise for any mistakes in my English.

Thanks a lot

**Comment by M66B** [comment]
Questions should be asked in the XDA XPrivacy forum.
In short: there will be updates only when there are critical problems. This has been explained several times in the XDA forum.
