### ISSUE TITLE
bug in connecting to internet

### ISSUE THREAD

**Issue by hmdtop** [M66B/XPrivacy#2357]
Hi
i disable connecting to internet for telegram or google chrome, but i dosent work and both of the apps can use internet i am using 3.6.19(481) version.

**Comment by M66B** [comment]
This has been discussed numerous times on XDA.
Enable the restriction 'inet', restart the application and the application has no internet access anymore.
If you want granular control over the internet access of an application, you should use a firewall application, like my own [NetGuard](https://github.com/M66B/NetGuard/).
There is also information about this in the FAQ.

**Comment by M66B** [comment]
Please read also this: https://github.com/M66B/XPrivacy#support
