### ISSUE TITLE
Restricting single functions?

### ISSUE THREAD

**Issue by Waester** [M66B/XPrivacy#2360]
Hey,

I've been wondering if it is possible to restrict single functions without having to tick the category first.

At the moment everytime I want to restrict Wifi.getScanResults under Location I have to tick the category, which automatically restricts all non-dangerous functions, and then clear the unwanted restrictions to achieve my needs.

**Comment by Gitoffthelawn** [comment]
+1

I don't think there is currently a way to do this, but I would like that functionality as well.

**Comment by M66B** [comment]
Functions are in fact exceptions to the category for performance reasons, so this is and will not possible.

Please read this:
https://github.com/M66B/XPrivacy#support
