### ISSUE TITLE
Losing Contact restrictions for Whatsapp

### ISSUE THREAD

**Issue by christianrj** [M66B/XPrivacy#2363]
I have Xprivacy PRO installed (latest version 3.6.19).

I set XPrivacy to restrict contacts to Whatsapp , but he loses the restricted contact settings all the time.

I need to reconfigure the contact restrictions for Whatsapp on XPrivacy all the time, which is very annoying.

It was working without problems on Android 5.0, but after upgrade to 6.0.1, started to show these problems.

How to fix this? Thank you!

Android: 6.0.1
Device: Galaxy S5 Duos (SM-G900FD)
Xprivacy: PRO 3.6.19
Xposed: 86.0 (built by wanam for Samsung devices)

**Comment by M66B** [comment]
This has been discussed a few times on the XDA XPrivacy forum, so please have a look there.

**Comment by c33s** [comment]
@M66B had a look in the [forum][1] but over 8500 posts are quite a lot. even searching for "whatsapp" returns over 260 results.
would you mind to add a direct link, where an info about that could be found? or maybe add it to the [faq][2]?

[1]: http://forum.xda-developers.com/xposed/modules/xprivacy-ultimate-android-privacy-app-t2320783
[2]: https://github.com/M66B/XPrivacy#frequently-asked-questions-faq

**Comment by christianrj** [comment]
I confirm this bug still present. Today I upgraded my phone (Galaxy S5) to 6.0.1 again (stock, fresh install via Odin) and after allowing some contacts in Xprivacy for Whatsapp, it works, but after some time, Whatsapp lose the permission to access that contacts automatically.

It's not possible to have a look at this bug and fix it? Thank you!
