### ISSUE TITLE
Cannot restrict firefox for specific urls

### ISSUE THREAD

**Issue by c33s** [M66B/XPrivacy#2364]
specs overview:
- xprivacy 3.6.19 (481) (pro version)
- xposed version 86 - 3.0 alpha4
- CyanogenMod for the Galaxy S4 Mini - cm-13.0-20160418-SNAPSHOT-ZNH0EAO2NJ-serranoltexx.zip
- rooted via CyanogenMod
- AFWall+ (root firefall)

on my old CM installation i was able to restrict or allow the access to specific urls for an app.

with the new installation, when i try to restrict the access for firefox for a specific url it does not work. clearing all rules for firefox in xprivacy and then starting firefox invokes the xprivacy dialog for some sections (nfc, accounts,..) and then `InetAddress.getAllByName` for `*.services.mozilla.com` appears. if i choose deny, i would assume to block access to this url. when i enter a url, for example, `google.com` the dialog is invoked again, i blacklist the url/domain again but in the background i can see the pages gets loaded.

should it be possible to block the access to urls like this? should it work or do i miss something?

**Comment by M66B** [comment]
XPrivacy cannot granularly restrict internet access done through native libraries. This is better done using a real firewall application like AFWall+ or NetGuard.

**Comment by c33s** [comment]
the problem is, that xprivacy is the only app, which is able to restrict also via ip&port. 
all the other apps i know (except https://play.google.com/store/apps/details?id=app.greyshirts.firewall&hl=en) are only able to allow or disallow internet access.

any other options than xprivacy?

**Comment by M66B** [comment]
How about NetGuard?

Julian <notifications@github.com> schreef op 19 augustus 2016 11:17:41 CEST:

**Comment by c33s** [comment]
if NetGuard wouldn't block my vpn service (need it for openvpn), i would instantly buy the donate version.
so i am looking for a root firewall/some tool which support this kind of blocking. my currently firewall lacks this feature https://github.com/ukanth/afwall/issues/15
i thought that xprivacy is the way to go :) (thank you for this great app)

**Comment by migueldemoura** [comment]
@M66B, I've been struggling with this as well: afwall+ doesn't allow one to block specific domains/subdomains and netguard, although a much superior alternative to the abandoned NoRootFirewall (last release in 2014), doesn't seem to bolster one great feature of this latter app:
- Allow/Block a specific port or a specific domain/subdomain (if I get requests to example$ID.googlevideo.com, I can't set a rule for the entire domain, only manually to each accessed subdomain)

This last issue is a huge pain point and one that isn't properly addressed by none of the available firewall apps.

**Comment by M66B** [comment]
This is the XPrivacy GitHub, but out of courtesy I will answer you: NetGuard does not and will not support wildcards for performance and battery usage reasons. However, you can block individual domains (including port).

For your next NetGuard support questions, please go here:
https://forum.xda-developers.com/android/apps-games/app-netguard-root-firewall-t3233012
