### ISSUE TITLE
No popup asking for allow/deny

### ISSUE THREAD

**Issue by wimg** [M66B/XPrivacy#2367]
After doing a factory reset, installing X-Posed and X-Privacy, I don't get any popups anymore asking for allow/deny.
X-Privacy is activated in X-Posed and the phone has been rebooted. It loads fine, but I get no popups asking for permissions at all.

Any idea what might be wrong ? I already tried removing and reinstalling and even removed /data/system/xprivacy and then reinstalled

**Comment by M66B** [comment]
Please read this: https://github.com/M66B/XPrivacy/#support
