### ISSUE TITLE
error on miui 8

### ISSUE THREAD

**Issue by xdarknet** [M66B/XPrivacy#2372]
Haii im using xiaomi redmi 3s, launch marsmallow 6.0.1 and Miui 8 os. But if im enable xprivacy on xposed, almost all apps showing floating window is force close. Can you helpme?
Xposed intaller force close too after enable or disable some modules, for good testing is titamium backup apps thats app always force close. But if xprivacy not enable its not error or force close

**Comment by M66B** [comment]
Please provide a logcat.

**Comment by xdarknet** [comment]
Im wait for miui 8 global sir. Im testing on miui 8 beta. I will give
logcat if im on miui 8 global. Nom im in miui 7 because its stable for
using xprivacy
