### ISSUE TITLE
Restricting access to certain directories

### ISSUE THREAD

**Issue by T-vK** [M66B/XPrivacy#2377]
Some apps require Storage access, but they only really need access to one folder. Nevertheless I have to grant access to all my files. This becomes an issue for me when the app requires Internet permissions. 

What is your stance on that?

**Comment by Gitoffthelawn** [comment]
+1

**Comment by gittehubble128** [comment]
+1

**Comment by T-vK** [comment]
Holy cow, I just realized something. This feature is already available. 
Every time you get a pop up from Xprivacy, you can check the "Expert Mode" checkbox. When you enable that, Xprivacy will tell you which folder exactly an app is trying to get access. Then you can simply whitelist/blacklist the folder.  
Using the Pro version, which I just bought, you can actually view and modify these white/black lists. Very neat.
