### ISSUE TITLE
Does not work for Android 6.0.1

### ISSUE THREAD

**Issue by exotfboy** [M66B/XPrivacy#2378]
I am using Android 6.0.1 with xprivacy 3.6.19, and this is the first time I use xprivacy.

After I installed an app name `FileManager` I grant it the `storage` permission through the android setting--app permissions. 

![image](https://cloud.githubusercontent.com/assets/16457917/19218978/244aaa90-8e3a-11e6-86a4-55fc934f5922.png)

Then restrict all the permissions in xprivacy:
![image](https://cloud.githubusercontent.com/assets/16457917/19218981/31d278fa-8e3a-11e6-966f-e5df71d162d6.png)

In my opinion, this should prevent the app` FileManager` reading anything from the storage, however once I open the app, it can still show the folders and files. What's going on?

And what is the priority between the Android native permission(through setting) control and xprivacy?

Also, each time I open xprivacy, it will open the verison, guideline dialog, just like it is the first time I run this app.

Someone meet the same situation?

**Comment by Gitoffthelawn** [comment]
@M66B If you like, I can update the FAQ with the minimum Xposed version required.  Just let me know what it is, and if it differs for each version of Android, and I'll update the FAQ accordingly for you.

**Comment by M66B** [comment]
XPrivacy will report if the Xposed version is out of date.
The problem is people using the wrong Xposed version or a buggy Xposed version hacked together by someone. This fragmented Xposed development is also the reason why there will be only updates if there are critical bugs found, because basically the foundation of XPrivacy is broken.

**Comment by Gitoffthelawn** [comment]
Yes, hopefully someday there will be a simple repo with the latest stable version of Xposed for each Android release.  For people not familiar with the framework, it must be very confusing.

**Comment by exotfboy** [comment]
I follow this tutorial:

https://devs-lab.com/how-to-install-system-less-xposed-in-android.html

And install xpose of "xposed-v86.6-sdk23-topjohnwu.zip".
