### ISSUE TITLE
Bitcoin Payments Support

### ISSUE THREAD

**Issue by AlphaOmega3** [M66B/XPrivacy#2385]
Hi! First, although I am a happy user of your app, I would like to ask a added: the ability (for the free version of XPrivacy), to unlock the "pro" version using bitcoins .. since I don't use the Play Store and I don't want to get started now. Greetings.

**Comment by M66B** [comment]
Please see here: https://www.xprivacy.eu/

**Comment by AlphaOmega3** [comment]
Thank you!
