### ISSUE TITLE
More Mask Device Option

### ISSUE THREAD

**Issue by AlphaOmega3** [M66B/XPrivacy#2387]
Hi! Is possible add the ability to change this??

Model
Brand
Manufacturer
Board
Name
Device
OS_Version
Display_Id
Fingerprint

Bluetooth_Mac

And, for support this settings:
+ add "backup" button for save original information;
+ add "restore personal information" button; 
+ add the abikity, when you change the identity of the device, to see the new information also in the settings (such as device ID changer + device faker plus), in order, you could add these permissions:

WRITE_SETTINGS (to see the changes apply)
READ_PHONE_STATE
BLUETOOTH
ACCESS_NETWORK_STATE
ACCESS_WIFI_STATE

**Comment by M66B** [comment]
Please see the FAQ.
