### ISSUE TITLE
Restrict to request does not work (pop up window)

### ISSUE THREAD

**Issue by Zalier** [M66B/XPrivacy#2391]
Hello everyone, my problem is that the option to allow or deny permissions does not work (pop up window) try to reinstall the android stock and install other ROMs based on it, I can not make that option work.

Additional data: Xperia S (lt26i) with Android 4.1.2, USB debugging turned on, Device Management enabled, Xposed On, try with Xprivacy Free and paid, Busybox 1.24 Stericcson.

**Comment by M66B** [comment]
Please read the support section on GitHub.
