### ISSUE TITLE
Kontakte für Zugriff sperren - keine Kontakte

### ISSUE THREAD

**Issue by JosefUcker** [M66B/XPrivacy#2394]
Cyangemod, Android 4.4.4
Xprivacy Pro

Hallo,
bei einer App habe ich die Kontakte gesperrt.
Gehe ich dann für eine selektve Freigabe auf "Kontakte für Zugriff sperren" erscheint nur die Meldung "Alle "Einstellungen".
Bei "Positivlisten verwalten" steht nichts.

Kontakte sind Phone und Google Konto.
Habe auch schon eine Gruppe all angelegt - einfach nur Leere...

Was tun?

**Comment by M66B** [comment]
Was tun? Read here: https://github.com/M66B/XPrivacy#support
