### ISSUE TITLE
java.lang.UnsatisfiedLinkError: XPrivacy

### ISSUE THREAD

**Issue by jehy** [M66B/XPrivacy#2395]
[My application](https://github.com/jehy/rutracker-free) is crashing because of XPrivacy. I don't know many details since it's not my phone and I only have stack trace. Stack trace is the following (look where begins `Caused by java.lang.UnsatisfiedLinkError: XPrivacy`):

> Fatal Exception: java.lang.RuntimeException: Unable to resume activity {ru.jehy.rutracker_free/ru.jehy.rutracker_free.MainActivity}: android.view.InflateException: Binary XML file line #34: Error inflating class ru.jehy.rutracker_free.RutrackerWebView
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3390)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3421)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)
>        at android.app.ActivityThread.access$900(ActivityThread.java:177)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:5938)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
>        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
> Caused by android.view.InflateException: Binary XML file line #34: Error inflating class ru.jehy.rutracker_free.RutrackerWebView
>        at android.view.LayoutInflater.createView(LayoutInflater.java:640)
>        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
>        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.view.LayoutInflater.inflate(<Xposed>)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
>        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
>        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
>        at ru.jehy.rutracker_free.MainActivity.onResume(MainActivity.java:148)
>        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
>        at android.app.Activity.performResume(Activity.java:6406)
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3379)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3421)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)
>        at android.app.ActivityThread.access$900(ActivityThread.java:177)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:5938)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
>        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
> Caused by java.lang.reflect.InvocationTargetException
>        at java.lang.reflect.Constructor.newInstance(Constructor.java)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
>        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
>        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
>        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.view.LayoutInflater.inflate(<Xposed>)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
>        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
>        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
>        at ru.jehy.rutracker_free.MainActivity.onResume(MainActivity.java:148)
>        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
>        at android.app.Activity.performResume(Activity.java:6406)
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3379)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3421)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)
>        at android.app.ActivityThread.access$900(ActivityThread.java:177)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:5938)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
>        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
> Caused by android.util.AndroidRuntimeException: java.lang.RuntimeException: Cannot load WebView
>        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:117)
>        at android.webkit.WebView.getFactory(WebView.java:2193)
>        at android.webkit.WebView.ensureProviderCreated(WebView.java:2188)
>        at android.webkit.WebView.setOverScrollMode(WebView.java:2247)
>        at android.view.View.<init>(View.java:3785)
>        at android.view.View.<init>(View.java:3899)
>        at android.view.ViewGroup.<init>(ViewGroup.java:507)
>        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
>        at android.webkit.WebView.<init>(WebView.java:547)
>        at android.webkit.WebView.<init>(WebView.java:492)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at android.webkit.WebView.<init>(WebView.java:475)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at android.webkit.WebView.<init>(WebView.java:462)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at ru.jehy.rutracker_free.RutrackerWebView.<init>(RutrackerWebView.java:30)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
>        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
>        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
>        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.view.LayoutInflater.inflate(<Xposed>)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
>        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
>        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
>        at ru.jehy.rutracker_free.MainActivity.onResume(MainActivity.java:148)
>        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
>        at android.app.Activity.performResume(Activity.java:6406)
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3379)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3421)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)
>        at android.app.ActivityThread.access$900(ActivityThread.java:177)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:5938)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
>        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
> Caused by java.lang.RuntimeException: Cannot load WebView
>        at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:5054)
>        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:187)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java)
>        at java.lang.Class.newInstance(Class.java:1650)
>        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:112)
>        at android.webkit.WebView.getFactory(WebView.java:2193)
>        at android.webkit.WebView.ensureProviderCreated(WebView.java:2188)
>        at android.webkit.WebView.setOverScrollMode(WebView.java:2247)
>        at android.view.View.<init>(View.java:3785)
>        at android.view.View.<init>(View.java:3899)
>        at android.view.ViewGroup.<init>(ViewGroup.java:507)
>        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
>        at android.webkit.WebView.<init>(WebView.java:547)
>        at android.webkit.WebView.<init>(WebView.java:492)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at android.webkit.WebView.<init>(WebView.java:475)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at android.webkit.WebView.<init>(WebView.java:462)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at ru.jehy.rutracker_free.RutrackerWebView.<init>(RutrackerWebView.java:30)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
>        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
>        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
>        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.view.LayoutInflater.inflate(<Xposed>)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
>        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
>        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
>        at ru.jehy.rutracker_free.MainActivity.onResume(MainActivity.java:148)
>        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
>        at android.app.Activity.performResume(Activity.java:6406)
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3379)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3421)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)
>        at android.app.ActivityThread.access$900(ActivityThread.java:177)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:5938)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
>        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
> Caused by org.chromium.base.library_loader.ProcessInitException
>        at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:311)
>        at org.chromium.base.library_loader.LibraryLoader.loadNow(LibraryLoader.java:168)
>        at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:5048)
>        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:187)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java)
>        at java.lang.Class.newInstance(Class.java:1650)
>        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:112)
>        at android.webkit.WebView.getFactory(WebView.java:2193)
>        at android.webkit.WebView.ensureProviderCreated(WebView.java:2188)
>        at android.webkit.WebView.setOverScrollMode(WebView.java:2247)
>        at android.view.View.<init>(View.java:3785)
>        at android.view.View.<init>(View.java:3899)
>        at android.view.ViewGroup.<init>(ViewGroup.java:507)
>        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
>        at android.webkit.WebView.<init>(WebView.java:547)
>        at android.webkit.WebView.<init>(WebView.java:492)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at android.webkit.WebView.<init>(WebView.java:475)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at android.webkit.WebView.<init>(WebView.java:462)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at ru.jehy.rutracker_free.RutrackerWebView.<init>(RutrackerWebView.java:30)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
>        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
>        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
>        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.view.LayoutInflater.inflate(<Xposed>)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
>        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
>        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
>        at ru.jehy.rutracker_free.MainActivity.onResume(MainActivity.java:148)
>        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
>        at android.app.Activity.performResume(Activity.java:6406)
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3379)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3421)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)
>        at android.app.ActivityThread.access$900(ActivityThread.java:177)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:5938)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
>        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
> Caused by java.lang.UnsatisfiedLinkError: XPrivacy
>        at biz.bokhorst.xprivacy.XRuntime.a(SourceFile:81)
>        at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.beforeHookedMethod(SourceFile:628)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:653)
>        at java.lang.Runtime.loadLibrary(<Xposed>)
>        at java.lang.System.loadLibrary(System.java:989)
>        at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:297)
>        at org.chromium.base.library_loader.LibraryLoader.loadNow(LibraryLoader.java:168)
>        at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:5048)
>        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:187)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java)
>        at java.lang.Class.newInstance(Class.java:1650)
>        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:112)
>        at android.webkit.WebView.getFactory(WebView.java:2193)
>        at android.webkit.WebView.ensureProviderCreated(WebView.java:2188)
>        at android.webkit.WebView.setOverScrollMode(WebView.java:2247)
>        at android.view.View.<init>(View.java:3785)
>        at android.view.View.<init>(View.java:3899)
>        at android.view.ViewGroup.<init>(ViewGroup.java:507)
>        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
>        at android.webkit.WebView.<init>(WebView.java:547)
>        at android.webkit.WebView.<init>(WebView.java:492)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at android.webkit.WebView.<init>(WebView.java:475)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at android.webkit.WebView.<init>(WebView.java:462)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.webkit.WebView.<init>(<Xposed>)
>        at ru.jehy.rutracker_free.RutrackerWebView.<init>(RutrackerWebView.java:30)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
>        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
>        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
>        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
>        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
>        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:673)
>        at android.view.LayoutInflater.inflate(<Xposed>)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
>        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
>        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
>        at ru.jehy.rutracker_free.MainActivity.onResume(MainActivity.java:148)
>        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
>        at android.app.Activity.performResume(Activity.java:6406)
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3379)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3421)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)
>        at android.app.ActivityThread.access$900(ActivityThread.java:177)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:5938)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
>        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)

**Comment by M66B** [comment]
This is caused by a restriction and an expected crash if the app cannot handle the exception.
Please see here if you have questions about this: https://github.com/M66B/XPrivacy#support

**Comment by jehy** [comment]
But I'm just trying to initiialize webview and Xprivacy breaks initialization. There is no exception for me to handle - error is occuring in android libraries.
