### ISSUE TITLE
Too many devices

### ISSUE THREAD

**Issue by shanerogers297** [M66B/XPrivacy#2397]
I wasn't aware I had installed on 5 devices. I now only have one phone. Can I de-register the other devices? If so, what is the process? If not, I will buy another license, but that would be too complicated.
Great work...this is my very favorite app.

**Comment by M66B** [comment]
Please contact me for support on this by either using the support button in the XPrivacy pro license fetcher or by replying to the XPrivacy pro activation instructions.

GitHub issues are for features requests and bug reports regarding XPrivacy only.
