### ISSUE TITLE
Would it be possible for the XPrivacy community to get a dedicated forum?

### ISSUE THREAD

**Issue by T-vK** [M66B/XPrivacy#2401]
I find myself pretty often in situations where I have trouble getting something to work because of XPrivacy. I usually manage to resolve it myself somehow, but sadly I don't find myself sharing the gathered knowledge afterwards. Now I could of course go to the XPrivacy thread on XDA or to the Xposed module subforum and ask for help in the first place or create a helpful guide afterwards, but I usually don't because it is so unorganized and there is absolutely no structure. It's extremely hard to to find specific information and if you do it's usually deep inside of the gigantic XPrivacy thread. And if you ask a question in that thread you can't really subscribe to it without getting your inbox spammed to death every single time someone else asks a question or answers someone elses question. And the problem with the Xposed submodule forum is that the people who could help don't really monitor it; that includes myself.

I'm actually active in quite a few forums and am always more than willing to help others. I would really love to also help people using XPrivacy, resolving related issues and even create guides and tutorials (as I have solved quite a few problems that other people haven't or even thought to be impossible).  
But without proper organization and structuring of the information (dedicated threads for different problems, guides etc, multiple subforums, ...), I just have zero motivation to do anything.  

I think if we had a dedicated forum for XPrivacy we could create a great community of Android privacy enthusiasts and greatly help making XPrivacy more accessible to a wider audience, especially beginners.  

In case you are interested, I'd gladly help you out setting it up.

**Comment by M66B** [comment]
Once there was such a forum, but everybody kept use the XDA XPrivacy forum, so that didn't work.

**Comment by T-vK** [comment]
Well, I think that doesn't really matter too much. I mean at least people like me will use it. And even if it is just being used to create helpful guides I think it would be well worth it.  
But I think that if you just give it enough time it will be used by more people eventually.

**Comment by M66B** [comment]
It was given enough time and it still didn't work.

You can always start your own forum about XPrivacy if you like, but you will see there is no point in doing so.

**Comment by T-vK** [comment]
Well, besides that it "didn't work" is there really any disadvantage to having a dedicated forum?  
I could of course create an unofficial forum, but then I would have to pay for the hosting and the domain. :/

**Comment by M66B** [comment]
Hosting doesn't come free to me either.
Note that XPrivacy is basically free to use.

**Comment by T-vK** [comment]
Yes, I know that, but you're already hosting a website on xprivacy.eu, right? So there wouldn't really be any additional costs if we added a subdirectory for the forum to it. And you could always add a "keep alive donation button". I don't think that would work too well if the forum was unofficial.

**Comment by M66B** [comment]
I am sorry, but I am not going to put effort into this, since the last forum was a failure and it will likely be again.

**Comment by T-vK** [comment]
It doesn't really take any effort to set up a phpbb forum or something like that. And if you're talking about deleting spam on the forum etc, you can easily give other people permission to do that.

**Comment by M66B** [comment]
Setting up and maintaining a forum is not a zero effort.

As said the previous forum failed, mostly due to little activity. So, I don't think someone is going to fight spam and abuse day in day out.

Why not just start a new XDA thread? If it is useful to others, I will link it from the stay post.

**Comment by T-vK** [comment]
Well, I would help as much as I can. I mean if you'd temporarily give me ftp access to a subfolder and a mySQL database, I would set it all up.  
And spam isn't really a big problem in the first place if you disable guest posting and use a captcha for the registration. But even if, I would still be willing to help getting rid off it. Maybe not every day, but often enough. 

And about your last statement: I don't think that would work very well. I mean first of all I would probably be the only who knows that you can get your thread indexed in the xprivacy start post, secondly it would take a lot of effort for you in the long run and most importantly (imo) you're missing out on features of dedicated forums. So for instance you would not be able to subscribe to get email notifications whenever someone created a new guide.

**Comment by M66B** [comment]
For security reasons I am not giving any third party access to my servers.

**Comment by T-vK** [comment]
I understand that, but would it really take that much effort from your side to set it up?

**Comment by M66B** [comment]
As explained, the previous forum wasn't a success either, so I am simply not going to put effort into this.

**Comment by T-vK** [comment]
If I would rent a cheap server and set up an XPrivacy forum on it, would you be willing to give it a subdomain?

**Comment by M66B** [comment]
Since XPrivacy is a community project: sure, no problem, but there are two conditions:

* It should be made clear on all pages of the forum (for when somebody directly accesses a page through a search engine) that a third party (you) maintains the forum and not me.
* The forum software and contents should be maintained

I will remove the DNS-record if there is spam or outdated information on the forum for an extended period or when the forum is offline for an extended period. In that case there is no way to get the DNS-record back. The same will happen if people ask me personally too many times about the forum.

If you like, I will make a link in the start post of the XDA XPrivacy forum to your forum and you are allowed to post about the forum in the XDA XPrivacy thread a few times as well,but don't bother people too much.

**Comment by T-vK** [comment]
Thanks, that's great. I will get back to you when I found a VPS and have the forum set up.

**Comment by Gitoffthelawn** [comment]
@T-vK I agree with the observations you made in your first post above.

In addition to a forum, you can also contribute by adding to the FAQ, Wiki, and README here on GitHub.  I have done it extensively, and Marcel has been helpful with the process.  He also has been appreciative to receive help. :)

If you do get the forum up and running, creating a link to it (with a disclaimer that Marcel is not running it) in the Wiki and README will help drive traffic and increase activity.

BTW, I don't think having a subdomain on xprivacy.eu is essential.  I think it will help, but I don't think it's mandatory.  I think it's great that Marcel is giving you a subdomain, but if you want more control, using your own domain will be fine too.

I look forward to whatever you decide to do, and I appreciate your enthusiasm and generosity.
