### ISSUE TITLE
xprivacy pro - activation failed

### ISSUE THREAD

**Issue by shangjoe04** [M66B/XPrivacy#2404]
Hi there,
activation failed. xprivacy read the activation-code and shows for a short moment: Pro-Version. But nothimg happens - e.g. whitelist: Every time I was re-directed to the xprivacy-url instead of creating a whitelist.
Thanks for your help!

**Comment by M66B** [comment]
Please contact me by using the support button in the XPrivacy pro license fetcher or by replying to the e-mail with activation instructions.
