### ISSUE TITLE
Additional 00:00 in fake MAC address.

### ISSUE THREAD

**Issue by deadkira** [M66B/XPrivacy#2405]
Hello,
I found a problem with xprivacy. The MAC address that is being fed to apps contains additional 00:00 before the address that we want to feed.
I did some googling and found out this post here : https://github.com/M66B/XPrivacy/issues/2112
Could someone explain this behaviour?
Is there anyone else having this issue?

**Comment by M66B** [comment]
Please read the other issue and the support section on GitHub.

**Comment by deadkira** [comment]
Well, I didn't find any solution there that's why I asked here. Could you please explain how to fix this?
