### ISSUE TITLE
xprivacy service not found (x86)

### ISSUE THREAD

**Issue by 3dDelta** [M66B/XPrivacy#2407]
Hi, I have a tablet Chuwi Hi8 (Android 4.4.4 (API 19) and Windows 10).
I add and activate XPrivacy 3.6.19, reboot, but when you run XPrivacy reports "xprivacy service not found" 
CPU x86
Xposed Framework 58

**Comment by M66B** [comment]
Possible causes:
- XPrivacy not enabled in Xposed
- Incompatible Xposed version
- Incompatible Android version

If you want me to look into the cause, then I need a logcat of the first 30 seconds captured from your PC using adb.

For other support, please use the XDA XPrivacy forum.
