### ISSUE TITLE
Gmail message due to change mobile number

### ISSUE THREAD

**Issue by MarkoIndaco** [M66B/XPrivacy#2412]
As the title, Gmail keeps send me an alert e-mail (every f.....ing  minute) cause the different mobile number. Important to say is I NEVER GIVE MY PHONE NUMBER TO GOOGLE, so, this is a "service" that i NEVER request. I DON'T use 2-way security log-in.
Please resolve this cause that crap on MV still send me alert message.
This happens because I set XPrivacy to send random phone number every phone restart. Anyway, it occours also if I set the "deface" (standard) option. And it's new, cause I never got this issue before...
PS
I'm a donate-user

Sony Xperia E4g - Android 4.4.4

**Comment by M66B** [comment]
Please see the FAQ why this issue was closed.

**Comment by MarkoIndaco** [comment]
Hey, thank you for reply. Of course is not a bug, i know. This means that XPrivacy works as well. The problem is that crap Google. I'm trying to spoke with a real person on G. Nothing... and is so frustrating. They know ALL about ALL people, and no one can spoke with this xxxxxx.
It since from yesterday i recive (around) 20 email por minute (i'm not wrong) that ask "did you change phone number"?
Yes, i do, f....g G idiots!
I'm going to try some help in XDA. Hope, because my phone it's really become unsable cause alert email every 5/10 seconds...
