### ISSUE TITLE
[Feature request] spoofing HTTP responses on sockets created by the app. 

### ISSUE THREAD

**Issue by Freeedim** [M66B/XPrivacy#2413]
Hi and thanks for this great work!

I'm bad at programming and don't even know if my request is possible.

I would like to be able to set a HTTP response code that XPrivacy would give to an inet call. Some apps crash when inet is restricted (I know it is advertised as a dangerous restriction, but sometimes you really want your app not to go on that through that socket). Maybe if the app could create that socket and receive a HTTP404 or HTTP50x, it would get along with it.

Thanks for your attention (and again, for your work).
Cheers

**Comment by M66B** [comment]
For more granular internet control you should use a firewall app, like my [NetGuard](https://forum.xda-developers.com/android/apps-games/app-netguard-root-firewall-t3233012), see also the FAQ.
