### ISSUE TITLE
Newly installed applications aren't restricted by default after Pro activation

### ISSUE THREAD

**Issue by belidzs** [M66B/XPrivacy#2414]
I have acquired a Pro license, but since activation XPrivacy no longer restricts new applications by default. 

There might be a setting controlling this behavior but I was unable to find it.

I'm using v3.6.19 (481) in compatibility mode on Android 6.0.1 (MIUI 8.2.6)

**Comment by M66B** [comment]
Please ask your questions in the XDA forum.
https://github.com/M66B/XPrivacy#support

**Comment by M66B** [comment]
In any case the pro license has nothing to do with restricting apps by default.

**Comment by belidzs** [comment]
@M66B exactly this is why I thought this was a bug

**Comment by M66B** [comment]
XPrivacy has 100,000s of users, so this is quite unlikely.

**Comment by belidzs** [comment]
@M66B 
I was able to replicate this issue on my device twice with an uninstall-reinstall-activate cycle. No settings were changed in between. Even if this is caused by a bad setting, it was not intentionally set by me and thus it is a very unexpected behavior which should be fixed. 

I really don't think you should close an issue after 0 investigation but it is your project so this is probably what I have to live with. Thanks anyway for your work on this.
