### ISSUE TITLE
IPv6 Whitelisting: Enable Wildcards, Please

### ISSUE THREAD

**Issue by Grossdm** [M66B/XPrivacy#2415]
I've found that Xprivacy does not offer wildcard options for white/black-listing of IPv6 addresses, unlike how it does for IPv4 addresses (and domains, BTW).
This is very much needed, even more than it has been needed for IPv4.

I'm really hoping this doesn't get a "lowprio" tag. :-)

**Comment by M66B** [comment]
For managing internet connections you can better use a firewall app, like my [NetGuard](https://github.com/M66B/NetGuard/).

**Comment by Grossdm** [comment]
Thank you for the suggestion!
