### ISSUE TITLE
When is new update? 

### ISSUE THREAD

**Issue by ilker-binzet** [M66B/XPrivacy#2417]
I have translated and corrected Turkish translations. I am waiting for update for a long time to add a new translation file. So when is update?

**Comment by M66B** [comment]
The subject of updates had been discussed in the XDA XPrivacy forum several times.

**Comment by ilker-binzet** [comment]
I could not understand you.

**Comment by M66B** [comment]
About questions: https://github.com/M66B/XPrivacy#support
