### ISSUE TITLE
Android 7+ support?

### ISSUE THREAD

**Issue by ShapeShifter499** [M66B/XPrivacy#2419]
I'm sorry if I missed this information somewhere but are there any plans to support Android 7+ in some way? I know XPosed isn't on Android 7+ but isn't there a way to still provide support? 

I currently run LineageOS 14.1 on my Moto X Pure (clark) and I find the "Privacy Guard" isn't as great as XPrivacy. I can't run some apps without giving them full access to files or my phone sensors even when they don't need that sort of blanket permission to run. I used to run XPrivacy but that was before I needed the newer Android OS to run stuff and stay more secure with updates.

**Comment by M66B** [comment]
This has been discussed several times in the XDA XPrivacy thread.

Please read this too: https://github.com/M66B/XPrivacy#support
