### ISSUE TITLE
Bootloop on LeeDroidM9 and ViperOneM9

### ISSUE THREAD

**Issue by MarkoIndaco** [M66B/XPrivacy#2426]
Hi guys, as the title post I try yesterday to run Xprivacy on LeeDroid and ViperOne, but no luck. Xposed works, and also it install Xprivacy module but, once you tick to activate, and reboot the phone, this drop into bootloop. I made a clean flash both roms **LeeDrOiD M9 v8.3.0 (Port from LeeDrOiD 10 - Nougat)** and **ViperOneM9 6.1.0** Any idea on what it may be?

**Comment by M66B** [comment]
This question doesn't belong here, please read: https://github.com/M66B/XPrivacy#support

You are most likely using a buggy Xposed version.
