### ISSUE TITLE
GSF ID

### ISSUE THREAD

**Issue by thelimper** [M66B/XPrivacy#802]
Hey. Trying to mask my GSF ID and having no luck at all. I've tried randomizing it and typing one but it does not actually mask it. I'm checking via [Android Device ID](https://play.google.com/store/apps/details?id=com.evozi.deviceid) app. 

I'm running a 4.3ROM and have had the same issue in the past. Everything else seems to work fine. I have latest versions I stalled and all is good to go. Should I try force stopping Google services or something?

I know I have the app set up correctly. Its simply not changing the GSF ID.

**Comment by jackman1234** [comment]
I had this same problem and this fixed it.
